begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,is_anonymous,raw_user_meta_data) values
('a9910000-0000-4000-8000-000000000001','activity-one@example.test',false,'{"character_name":"ActivityCaptain"}'),
('a9910000-0000-4000-8000-000000000002','activity-two@example.test',false,'{"character_name":"ActivityOther"}'),
('a9910000-0000-4000-8000-000000000003','activity-anon@example.test',true,'{}');
create temporary table activity_fixture as select
(select id from public.characters where user_id='a9910000-0000-4000-8000-000000000001') a,
(select id from public.characters where user_id='a9910000-0000-4000-8000-000000000002') b,
gen_random_uuid() request;
grant select on activity_fixture to authenticated;
create temporary table activity_results(key text primary key,value jsonb);
grant all on activity_results to authenticated;
update public.characters set stamina=20,stamina_updated_at=clock_timestamp()+interval '1 day',
  energy=100,energy_updated_at=clock_timestamp()+interval '1 day' where id in(select a from activity_fixture union all select b from activity_fixture);
-- Make catches deterministic within this rolled-back fixture; misses are tested explicitly below.
update private.activity_loot set success_start=100,success_end=100 where activity_id in('shore_fishing','woodland_logging');
set local role anon;
select throws_ok($$select public.perform_activity('shore_fishing',1,10,gen_random_uuid())$$,'42501',null,'Logged-out users cannot do activities');
reset role;
select set_config('request.jwt.claims','{"sub":"a9910000-0000-4000-8000-000000000003","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select public.perform_activity('shore_fishing',1,10,gen_random_uuid())$$,'42501',null,'Anonymous Auth users cannot do activities');
reset role;
select set_config('request.jwt.claims','{"sub":"a9910000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
insert into activity_results select 'first',public.perform_activity('shore_fishing',1,10,request) from activity_fixture;
select is((select (value->>'stamina_cost')::integer from activity_results where key='first'),1,'Fishing costs one Stamina');
select is((select (value->>'xp_awarded')::integer from activity_results where key='first'),10,'Fishing awards ten XP');
select is((select value->>'skill_id' from activity_results where key='first'),'fishing','Fishing awards its own skill');
select is((public.get_game_state()->>'stamina')::integer,19,'Stamina is deducted');
select is((public.get_game_state()->>'energy')::integer,100,'Activities do not consume Energy');
select is((select public.perform_activity('shore_fishing',1,10,request) from activity_fixture),(select value from activity_results where key='first'),'Replay returns the same receipt');
select is((public.get_game_state()->>'stamina')::integer,19,'Replay never charges twice');
select throws_ok($$select public.perform_activity('coastal_foraging',1,10,request) from activity_fixture$$,'22023','REQUEST_CONFLICT','An ID cannot switch activities');
select throws_ok($$select public.perform_activity('shore_fishing',1,11,request) from activity_fixture$$,'22023','REQUEST_CONFLICT','An ID cannot switch its reward');
select public.perform_activity('shore_fishing',1,10,gen_random_uuid()) from generate_series(1,8);
select is((public.get_game_state()->>'stamina')::integer,11,'Nine actions cost nine Stamina');
select is((public.get_own_skills()->>'character_level')::integer,7,'Nine attempts stay below the new first level threshold');
select public.perform_activity('coastal_foraging',1,10,gen_random_uuid());
select public.perform_activity('woodland_logging',1,10,gen_random_uuid());
select is((public.get_game_state()->>'stamina')::integer,9,'Foraging and logging have the same cost');
select throws_ok('select * from private.activity_requests','42501',null,'Activity receipts remain private');
select throws_ok($$select public.perform_activity('unknown',1,10,gen_random_uuid())$$,'22023','INVALID_ACTIVITY','Unknown activities are rejected');
select throws_ok($$select public.perform_activity('shore_fishing',0,10,gen_random_uuid())$$,'22023','INVALID_REQUEST','Zero-cost forgery is rejected');
select throws_ok($$select public.perform_activity('shore_fishing',1,10.5,gen_random_uuid())$$,'22023','INVALID_REQUEST','Fractional XP is rejected');
select throws_ok($$select public.perform_activity('shore_fishing',1,'NaN',gen_random_uuid())$$,'22023','INVALID_REQUEST','Non-finite XP is rejected');
select throws_ok($$select public.perform_activity('shore_fishing',1,9999,gen_random_uuid())$$,'P0001','STALE_OFFER','Client cannot choose its XP reward');
select throws_ok($$select public.perform_activity('shore_fishing',2,10,gen_random_uuid())$$,'P0001','STALE_OFFER','Stale costs are rejected');
reset role;
select is((select xp from private.character_skills where character_id=(select a from activity_fixture) and skill_id='fishing'),90::bigint,'Fishing progression is exact');
select is((select xp from private.character_skills where character_id=(select a from activity_fixture) and skill_id='foraging'),10::bigint,'Foraging has separate XP');
select is((select xp from private.character_skills where character_id=(select a from activity_fixture) and skill_id='logging'),10::bigint,'Logging has separate XP');
select is((select count(*) from private.activity_requests where character_id=(select a from activity_fixture)),11::bigint,'Only successful unique actions create receipts');
select is((select coalesce(sum(quantity),0) from private.item_stacks where character_id=(select a from activity_fixture)),(select coalesce(sum((result#>>'{loot,quantity}')::numeric),0) from private.activity_requests where character_id=(select a from activity_fixture)),'Inventory loot matches the saved activity receipts');
update private.activity_definitions set active=false where id='shore_fishing';
set local role authenticated;
select is((select public.perform_activity('shore_fishing',1,10,request) from activity_fixture),(select value from activity_results where key='first'),'Old receipt survives a disabled activity');
select throws_ok($$select public.perform_activity('shore_fishing',1,10,gen_random_uuid())$$,'22023','INVALID_ACTIVITY','Disabled activities reject new actions');
reset role;
update private.activity_definitions set active=true,xp_gain=20 where id='shore_fishing';
set local role authenticated;
select is((select public.perform_activity('shore_fishing',1,10,request) from activity_fixture),(select value from activity_results where key='first'),'Old receipt survives a reward change');
select throws_ok($$select public.perform_activity('shore_fishing',1,10,gen_random_uuid())$$,'P0001','STALE_OFFER','Old offers cannot purchase the new reward');
reset role;
update private.activity_definitions set xp_gain=10 where id='shore_fishing';
update public.characters set stamina=0 where id=(select a from activity_fixture);
set local role authenticated;
select throws_ok($$select public.perform_activity('shore_fishing',1,10,gen_random_uuid())$$,'P0001','INSUFFICIENT_STAMINA','Empty Stamina blocks activity');
reset role;
select is((select xp from private.character_skills where character_id=(select a from activity_fixture) and skill_id='fishing'),90::bigint,'Rejected action gives no XP');
update public.characters set stamina_updated_at=clock_timestamp()-interval '1 day' where id=(select a from activity_fixture);
set local role authenticated;
select is((public.perform_activity('shore_fishing',1,10,gen_random_uuid())->>'stamina_after')::integer,49,'Recovered Stamina funds activity');
reset role;
savepoint activity_rollback;
select public.perform_activity('shore_fishing',1,10,gen_random_uuid());
rollback to savepoint activity_rollback;
select is((select xp from private.character_skills where character_id=(select a from activity_fixture) and skill_id='fishing'),100::bigint,'Transaction rollback removes the XP reward');
select is((select stamina from public.characters where id=(select a from activity_fixture)),49,'Transaction rollback restores Stamina');
select is((select count(*) from private.activity_requests where character_id=(select a from activity_fixture)),12::bigint,'Transaction rollback removes the receipt');
update private.activity_loot set success_start=0,success_end=0 where activity_id='shore_fishing';
set local role authenticated;
insert into activity_results select 'miss',public.perform_activity('shore_fishing',1,10,gen_random_uuid());
select is((select value#>>'{loot,caught}' from activity_results where key='miss'),'false','A missed catch is recorded as a failure');
select is((select (value->>'xp_awarded')::integer from activity_results where key='miss'),5,'A miss grants half the XP');
reset role;
update private.activity_definitions set xp_gain=1 where id='shore_fishing';
set local role authenticated;
select is((public.perform_activity('shore_fishing',1,1,gen_random_uuid())->>'xp_awarded')::integer,1,'A miss always grants at least one XP');
reset role;
update private.activity_definitions set xp_gain=10 where id='shore_fishing';
update private.activity_loot set success_start=100,success_end=100 where activity_id='shore_fishing';
select is((select xp from private.character_skills where character_id=(select a from activity_fixture) and skill_id='fishing'),106::bigint,'Misses add their reduced XP to the skill');
set local role authenticated;
insert into activity_results select 'combat',public.start_combat(b,gen_random_uuid()) from activity_fixture;
select throws_ok($$select public.perform_activity('shore_fishing',1,10,gen_random_uuid())$$,'P0001','IN_COMBAT','Combat blocks new activities');
select is((select public.perform_activity('shore_fishing',1,10,request) from activity_fixture),(select value from activity_results where key='first'),'A saved receipt can be checked during combat');
select public.submit_combat_order((value#>>'{battle,id}')::uuid,0,'retreat',gen_random_uuid()) from activity_results where key='combat';
reset role;
select set_config('request.jwt.claims','{"sub":"a9910000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select is((select (public.perform_activity('shore_fishing',1,10,request)->>'xp')::integer from activity_fixture),10,'The same UUID belongs to a separate receipt for another player');
select public.depart_harbor((public.get_game_state()#>>'{sea,version}')::uuid,gen_random_uuid());
select throws_ok($$select public.perform_activity('shore_fishing',1,10,gen_random_uuid())$$,'P0001','NOT_IN_HARBOR','Travel blocks shore activities');
select is((select (public.perform_activity('shore_fishing',1,10,request)->>'xp')::integer from activity_fixture),10,'A saved receipt can be checked while traveling');
reset role;
select set_config('request.jwt.claims','{"sub":"a9910000-0000-4000-8000-000000000001","role":"authenticated"}',true);
update public.characters set crew_health=0 where id=(select a from activity_fixture);
set local role authenticated;
select throws_ok($$select public.perform_activity('shore_fishing',1,10,gen_random_uuid())$$,'P0001','IN_HOSPITAL','Hospital blocks activity');
select is((select public.perform_activity('shore_fishing',1,10,request) from activity_fixture),(select value from activity_results where key='first'),'A saved receipt can be checked in hospital');
reset role;
select * from finish();
rollback;
