begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,is_anonymous,raw_user_meta_data) values
('ae110000-0000-4000-8000-000000000001','loot-admin@example.test',false,'{"character_name":"LootAdmin"}'),
('ae110000-0000-4000-8000-000000000002','loot-player@example.test',false,'{"character_name":"LootPlayer","is_admin":true}');
insert into private.admin_members(user_id) values('ae110000-0000-4000-8000-000000000001');
create temporary table loot_fixture as select
  (select id from public.characters where user_id='ae110000-0000-4000-8000-000000000002') captain,gen_random_uuid() request;
create temporary table loot_saved(key text primary key,value jsonb);
grant all on loot_saved to authenticated; grant select on loot_fixture to authenticated;
update public.characters set stamina=50,stamina_updated_at=clock_timestamp()+interval '1 day';
select set_config('request.jwt.claims','{"sub":"ae110000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select public.admin_get_loot_table('harbor_shore')$$,'42501','ADMIN_REQUIRED','Ordinary players cannot read loot administration');
select throws_ok($$select public.admin_mutate('save_item','{}',gen_random_uuid(),'Unauthorized creation')$$,'42501','ADMIN_REQUIRED','Metadata cannot grant content access');
select throws_ok($$select * from private.loot_entries$$,'42501',null,'Loot entries are private');
select throws_ok($$select private.loot_distribution('harbor_shore',1,99)$$,'42501',null,'Probability helper is not client-callable');
select throws_ok($$select private.admin_save_item('{}')$$,'42501',null,'Content helper cannot bypass the audit');
reset role;
select is((select count(*) from private.item_definitions where id in ('sprat','sardine','mackerel','sea_bass','red_snapper','silver_ring')),6::bigint,'Five fish and a ring exist');
select ok((select bool_and(image_path='/images/items/placeholder.svg') from private.item_definitions where id in ('sprat','sardine','mackerel','sea_bass','red_snapper','silver_ring')),'New items share the default image');
select ok((select bool_and(d.chance=1) from generate_series(1,99) l cross join lateral private.loot_distribution('harbor_shore',l,99) d where d.item_id='silver_ring'),'Ring remains exactly one percent at every level');
select is((select chance from private.loot_distribution('harbor_shore',1,99) where item_id='sprat'),39.6::numeric,'Low-level fish weight is normalized after the ring');
select is((select chance from private.loot_distribution('harbor_shore',99,99) where item_id='red_snapper'),14.85::numeric,'High-level fish receives its increased weight');
select ok((select bool_and(abs(total-100)<0.00000001) from (select sum(d.chance) total from generate_series(1,99) l cross join lateral private.loot_distribution('harbor_shore',l,99) d group by l) sums),'All levels sum to one complete catch');

select set_config('request.jwt.claims','{"sub":"ae110000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select is(public.admin_get_loot_table('harbor_shore')->>'name','Harbor Shore','Admin reads complete loot table');
select throws_ok($$select public.admin_mutate('save_item','{"id":"new"}',gen_random_uuid(),'Reserved item ID')$$,'22023','INVALID_CONTENT_ID','Creation route is not a usable item ID');
select throws_ok($$select public.admin_mutate('save_loot_table','{"id":"new"}',gen_random_uuid(),'Reserved table ID')$$,'22023','INVALID_CONTENT_ID','Creation route is not a usable table ID');
insert into loot_saved values('item_payload','{"id":"test_pearl","name":"Pearl","description":"A smooth pearl.","category_id":"miscellaneous","kind":"passive","slot":"none","active":true,"tradable":true}');
insert into loot_saved select 'item',public.admin_mutate('save_item',value,request,'Create a pearl') from loot_saved cross join loot_fixture where key='item_payload';
select is((select public.admin_mutate('save_item',value,request,'Create a pearl') from loot_saved cross join loot_fixture where key='item_payload'),(select value from loot_saved where key='item'),'Repeated item creation returns the same audit receipt');
select throws_ok($$select public.admin_mutate('save_item','{}',request,'Create a pearl') from loot_fixture$$,'22023','REQUEST_CONFLICT','Changed payload cannot reuse the receipt');
reset role;
select is((select image_path from private.item_definitions where id='test_pearl'),'/images/items/placeholder.svg','Missing image uses shared default');
select ok((select managed_by_admin from private.item_definitions where id='test_pearl'),'Admin content retains ownership across config changes');
select is((select total from private.item_circulation where item_id='test_pearl'),0::numeric,'New item initializes circulation');
insert into loot_saved select 'item_edit',(select value from loot_saved where key='item_payload')||jsonb_build_object('version',md5(to_jsonb(i)::text)) from private.item_definitions i where id='test_pearl';
set local role authenticated;
select throws_ok($$select public.admin_mutate('save_item',value||'{"kind":"equipment","slot":"crew_weapon"}',gen_random_uuid(),'Change item shape') from loot_saved where key='item_edit'$$,'22023','ITEM_SHAPE_LOCKED','Existing item ownership shape is permanent');
select throws_ok($$select public.admin_mutate('save_item',value||'{"image_path":"https://example.com/tracker.png"}',gen_random_uuid(),'External image') from loot_saved where key='item_edit'$$,'23514',null,'Arbitrary external image paths are rejected');
select throws_ok($$select public.admin_mutate('save_item',value||'{"image_path":"/api/item-images/ae110000-0000-4000-8000-000000000001/ae110000-0000-4000-8000-000000000002.png"}',gen_random_uuid(),'Missing upload') from loot_saved where key='item_edit'$$,'22023','INVALID_IMAGE','Uploaded images must exist');
select public.admin_mutate('save_item',value||'{"name":"Polished Pearl"}',gen_random_uuid(),'Rename pearl') from loot_saved where key='item_edit';
select throws_ok($$select public.admin_mutate('save_item',value,gen_random_uuid(),'Stale edit') from loot_saved where key='item_edit'$$,'40001','STALE_ROW','Stale item edit cannot overwrite another edit');

insert into loot_saved values('table_payload','{"id":"test_loot","name":"Test Loot","description":"Fixture","active":true,"entries":[{"item_id":"test_pearl","mode":"fixed","fixed_chance":100,"weight_start":0,"weight_end":0,"quantity":3,"damage":0,"accuracy":0}]}');
insert into loot_saved select 'table',public.admin_mutate('save_loot_table',value,request,'Create loot table') from loot_saved cross join (select gen_random_uuid() request) ids where key='table_payload';
select is(jsonb_array_length(public.admin_get_loot_table('test_loot')->'entries'),1,'Admin saves complete table and entries together');
select throws_ok($$select public.admin_mutate('save_loot_table',value||'{"id":"invalid_loot","entries":[]}',gen_random_uuid(),'Empty table') from loot_saved where key='table_payload'$$,'22023','INVALID_LOOT','Empty tables cannot be saved');
select throws_ok($$select public.admin_mutate('save_loot_table',jsonb_set(value||'{"id":"invalid_loot"}','{entries,0,fixed_chance}','1'),gen_random_uuid(),'Incomplete table') from loot_saved where key='table_payload'$$,'22023','INVALID_LOOT_TOTAL','Fixed-only table must cover all catches');
select throws_ok($$select public.admin_mutate('save_loot_table',value||jsonb_build_object('id','invalid_loot','entries',(value->'entries')||(value->'entries')),gen_random_uuid(),'Duplicate item') from loot_saved where key='table_payload'$$,'23505',null,'Duplicate items cannot silently change fixed odds');
reset role;
select is((select count(*) from private.loot_tables where id='invalid_loot'),0::bigint,'Rejected edits leave no partial table');
insert into loot_saved select 'binding',to_jsonb(a) from private.activity_loot a where activity_id='shore_fishing';
set local role authenticated;
select public.admin_mutate('save_activity_loot',value||'{"loot_table_id":"test_loot","success_start":0,"success_end":0}',gen_random_uuid(),'Guarantee failure') from loot_saved where key='binding';
select throws_ok($$select public.admin_mutate('save_activity_loot',value,gen_random_uuid(),'Stale activity edit') from loot_saved where key='binding'$$,'40001','STALE_ROW','Activity edits check the original version');
select throws_ok($$select public.admin_mutate('save_loot_table',public.admin_get_loot_table('test_loot')||'{"active":false}',gen_random_uuid(),'Disable used table')$$,'22023','LOOT_IN_USE','A linked table cannot be disabled');
reset role;
insert into loot_saved select 'disable_item',(select value from loot_saved where key='item_payload')||jsonb_build_object('version',md5(to_jsonb(i)::text),'active',false) from private.item_definitions i where id='test_pearl';
set local role authenticated;
select throws_ok($$select public.admin_mutate('save_item',value,gen_random_uuid(),'Disable used item') from loot_saved where key='disable_item'$$,'22023','ITEM_IN_LOOT','Active loot cannot lose a referenced item');
reset role;

select set_config('request.jwt.claims','{"sub":"ae110000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
insert into loot_saved select 'miss',public.perform_activity('shore_fishing',1,10,gen_random_uuid());
select is((select value#>>'{loot,caught}' from loot_saved where key='miss'),'false','Success roll precedes even a guaranteed fixed item');
select is((select value->>'xp_awarded' from loot_saved where key='miss'),'10','A miss still grants ten XP');
select is((public.get_game_state()->>'stamina')::integer,49,'A miss costs one Stamina');
select is((public.list_inventory()->>'total')::integer,0,'A miss grants no items');
reset role;
update private.activity_loot set success_start=100,success_end=100 where activity_id='shore_fishing';
set local role authenticated;
insert into loot_saved select 'catch',public.perform_activity('shore_fishing',1,10,request) from loot_fixture;
select is((select value#>>'{loot,name}' from loot_saved where key='catch'),'Polished Pearl','A catch snapshots the item name');
select is((select value#>>'{loot,quantity}' from loot_saved where key='catch'),'3','Configured quantity is granted');
select is((select value#>>'{loot,skill_level}' from loot_saved where key='catch'),'1','Catch uses the level before XP award');
select is((public.list_inventory()#>>'{items,0,quantity}')::integer,3,'Loot appears in inventory');
select is((select public.perform_activity('shore_fishing',1,10,request) from loot_fixture),(select value from loot_saved where key='catch'),'Replay returns the exact catch without rerolling');
select is((public.list_inventory()#>>'{items,0,quantity}')::integer,3,'Replay does not duplicate items');
reset role;
select is((select total from private.item_circulation where item_id='test_pearl'),3::numeric,'Loot updates circulation atomically');
savepoint reward_rollback;
select public.perform_activity('shore_fishing',1,10,gen_random_uuid());
rollback to savepoint reward_rollback;
select is((select total from private.item_circulation where item_id='test_pearl'),3::numeric,'Rollback removes circulation and reward changes');
select is((select stamina from public.characters where id=(select captain from loot_fixture)),48,'Rollback restores Stamina');
select is((select xp from private.character_skills where character_id=(select captain from loot_fixture) and skill_id='fishing'),20::bigint,'Rollback restores XP');
update private.item_stacks set quantity=9007199254740990 where item_id='test_pearl';
set local role authenticated;
select throws_ok($$select public.perform_activity('shore_fishing',1,10,gen_random_uuid())$$,'P0001','INVENTORY_FULL','Stack overflow is a definite failure');
select is((public.get_game_state()->>'stamina')::integer,48,'Overflow never consumes Stamina');
reset role;
update private.loot_entries set mode='weighted',fixed_chance=0,weight_start=1,weight_end=1 where loot_table_id='test_loot';
update private.item_stacks set quantity=3 where item_id='test_pearl';
set local role authenticated;
select is(public.perform_activity('shore_fishing',1,10,gen_random_uuid())#>>'{loot,item_id}','test_pearl','Weighted fallback grants a configured item');
reset role;
update private.activity_loot set loot_table_id=null where activity_id='shore_fishing';
set local role authenticated;
select is((select public.perform_activity('shore_fishing',1,10,request) from loot_fixture),(select value from loot_saved where key='catch'),'Old receipt survives unlinking and rebalancing');
select is(public.perform_activity('shore_fishing',1,10,gen_random_uuid())->'loot','null'::jsonb,'An unlinked activity remains XP-only');
reset role;
select is((select count(*) from private.admin_audit where actor_id='ae110000-0000-4000-8000-000000000001'),4::bigint,'Only successful changes create audit rows');
delete from private.admin_members where user_id='ae110000-0000-4000-8000-000000000001';
select set_config('request.jwt.claims','{"sub":"ae110000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select public.admin_get_loot_table('test_loot')$$,'42501','ADMIN_REQUIRED','Revocation immediately removes content access');
reset role;
select * from finish();
rollback;
