begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,is_anonymous,raw_user_meta_data) values
('a9940000-0000-4000-8000-000000000001','craft-one@example.test',false,'{"character_name":"CraftCaptain"}'),
('a9940000-0000-4000-8000-000000000002','craft-two@example.test',false,'{"character_name":"CraftOther"}'),
('a9940000-0000-4000-8000-000000000003','craft-anon@example.test',true,'{}');
create temporary table craft_fixture as select
(select id from public.characters where user_id='a9940000-0000-4000-8000-000000000001') a,
(select id from public.characters where user_id='a9940000-0000-4000-8000-000000000002') b,
(select version from private.crafting_recipes where id='oak_plank') version,gen_random_uuid() request;
grant select on craft_fixture to authenticated;
create temporary table craft_results(key text primary key,value jsonb);
grant all on craft_results to authenticated;
update public.characters set energy=0,stamina=0,energy_updated_at=clock_timestamp()+interval '1 day',
  stamina_updated_at=clock_timestamp()+interval '1 day',morale_updated_at=clock_timestamp()+interval '1 day'
  where id in(select a from craft_fixture union all select b from craft_fixture);
insert into private.item_stacks(character_id,item_id,quantity) select a,'oak_logs',12 from craft_fixture;
insert into private.item_stacks(character_id,item_id,quantity) select b,'oak_logs',5 from craft_fixture;
create temporary table craft_before as select
(select total from private.item_circulation where item_id='oak_logs') logs,
(select total from private.item_circulation where item_id='oak_planks') planks,
(select gold_coins from public.characters where id=(select a from craft_fixture)) gold;
set local role anon;
select throws_ok('select public.list_crafting_recipes()','42501',null,'Logged-out users cannot read private crafting stock');
select throws_ok($$select public.craft_item('oak_plank',repeat('a',64),gen_random_uuid())$$,'42501',null,'Logged-out users cannot craft');
reset role;
select set_config('request.jwt.claims','{"sub":"a9940000-0000-4000-8000-000000000003","role":"authenticated"}',true);
set local role authenticated;
select throws_ok('select public.list_crafting_recipes()','42501',null,'Anonymous Auth users cannot read crafting stock');
select throws_ok($$select public.craft_item('oak_plank',repeat('a',64),gen_random_uuid())$$,'42501',null,'Anonymous Auth users cannot craft');
reset role;
select set_config('request.jwt.claims','{"sub":"a9940000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select is(public.list_crafting_recipes()#>>'{0,ingredients,0,owned}','12','Recipes show only the owner inventory');
select is(public.list_crafting_recipes()#>>'{0,ingredients,0,quantity}','5','Oak plank requires five logs');
select is(public.list_crafting_recipes()#>>'{0,output,quantity}','1','Recipe yields one plank');
select throws_ok('select * from private.crafting_requests','42501',null,'Receipts remain private');
select throws_ok('update private.crafting_ingredients set quantity=1','42501',null,'Players cannot choose material costs');
select throws_ok($$select public.craft_item('oak_plank',null,gen_random_uuid())$$,'22023','INVALID_REQUEST','Missing offer is rejected');
select throws_ok($$select public.craft_item('oak_plank',repeat('a',64),null)$$,'22023','INVALID_REQUEST','Missing receipt ID is rejected');
select throws_ok($$select public.craft_item('missing',version,gen_random_uuid()) from craft_fixture$$,'22023','INVALID_RECIPE','Unknown recipe is rejected');
select throws_ok($$select public.craft_item('oak_plank',repeat('a',64),gen_random_uuid())$$,'P0001','STALE_OFFER','Old or forged costs are rejected');
insert into craft_results select 'first',public.craft_item('oak_plank',version,request) from craft_fixture;
select is((select value#>>'{output,item_id}' from craft_results where key='first'),'oak_planks','Crafting uses the existing plank definition');
select is((select value#>>'{progression,xp_awarded}' from craft_results where key='first'),'10','Receipt records Crafting XP');
select is(public.list_crafting_recipes()#>>'{0,ingredients,0,owned}','7','Exactly five logs are consumed');
select is(public.list_crafting_recipes()#>>'{0,output,owned}','1','Plank arrives instantly in inventory');
select is((select public.craft_item('oak_plank',version,request) from craft_fixture),(select value from craft_results where key='first'),'Replay returns the identical saved receipt');
select throws_ok($$select public.craft_item('oak_plank',repeat('b',64),request) from craft_fixture$$,'22023','REQUEST_CONFLICT','A saved request cannot change its offer');
select throws_ok($$select public.craft_item('other',version,request) from craft_fixture$$,'22023','REQUEST_CONFLICT','A saved request cannot change recipe');
reset role;
select is((select quantity from private.item_stacks where character_id=(select a from craft_fixture) and item_id='oak_logs'),7::bigint,'Replay never consumes a second set of logs');
select is((select energy from public.characters where id=(select a from craft_fixture)),0,'Crafting needs no Energy');
select is((select stamina from public.characters where id=(select a from craft_fixture)),0,'Crafting needs no Stamina');
select is((select gold_coins from public.characters where id=(select a from craft_fixture)),(select gold from craft_before),'Crafting charges no gold');
select is((select xp from private.character_skills where character_id=(select a from craft_fixture) and skill_id='crafting'),10::bigint,'Crafting awards ten XP exactly once including receipt replay');
select is((select total from private.item_circulation where item_id='oak_logs'),(select logs-5 from craft_before),'Circulation tracks consumed logs');
select is((select total from private.item_circulation where item_id='oak_planks'),(select planks+1 from craft_before),'Circulation tracks new planks');
select ok(exists(select 1 from private.character_actions where character_id=(select a from craft_fixture)),'Crafting records Last action');
create temporary table craft_action_before as select last_action_at from private.character_actions where character_id=(select a from craft_fixture);
select public.craft_item('oak_plank',version,request) from craft_fixture;
select is((select last_action_at from private.character_actions where character_id=(select a from craft_fixture)),(select last_action_at from craft_action_before),'Receipt checks do not advance Last action');
select ok(exists(select 1 from public.player_game_events where character_id=(select a from craft_fixture)),'Crafting publishes a game refresh event');
update private.crafting_recipes set active=false where id='oak_plank';
set local role authenticated;
select is(jsonb_array_length(public.list_crafting_recipes()),0,'Disabled recipes are hidden');
select is((select public.craft_item('oak_plank',version,request) from craft_fixture),(select value from craft_results where key='first'),'Receipt survives disabled recipe');
select throws_ok($$select public.craft_item('oak_plank',version,gen_random_uuid()) from craft_fixture$$,'22023','INVALID_RECIPE','Disabled recipe rejects new crafting');
reset role;
update private.crafting_recipes set active=true where id='oak_plank';
update private.item_definitions set active=false where id='oak_logs';
set local role authenticated;
select is(jsonb_array_length(public.list_crafting_recipes()),0,'Unavailable material hides recipe');
select throws_ok($$select public.craft_item('oak_plank',version,gen_random_uuid()) from craft_fixture$$,'P0001','RECIPE_UNAVAILABLE','Disabled materials reject crafting');
reset role;
update private.item_definitions set active=true where id='oak_logs';
update private.item_stacks set quantity=9007199254740991 where character_id=(select a from craft_fixture) and item_id='oak_planks';
set local role authenticated;
select throws_ok($$select public.craft_item('oak_plank',version,gen_random_uuid()) from craft_fixture$$,'P0001','INVENTORY_FULL','Full output stack rejects crafting');
reset role;
select is((select quantity from private.item_stacks where character_id=(select a from craft_fixture) and item_id='oak_logs'),7::bigint,'Full output stack does not consume ingredients');
update private.item_stacks set quantity=1 where character_id=(select a from craft_fixture) and item_id='oak_planks';
savepoint craft_atomic;
select public.craft_item('oak_plank',version,gen_random_uuid()) from craft_fixture;
rollback to savepoint craft_atomic;
select is((select quantity from private.item_stacks where character_id=(select a from craft_fixture) and item_id='oak_logs'),7::bigint,'Rollback restores ingredients');
select is((select quantity from private.item_stacks where character_id=(select a from craft_fixture) and item_id='oak_planks'),1::bigint,'Rollback removes output');
select is((select count(*) from private.crafting_requests where character_id=(select a from craft_fixture)),1::bigint,'Rollback removes receipt');
select is((select xp from private.character_skills where character_id=(select a from craft_fixture) and skill_id='crafting'),10::bigint,'Transaction rollback restores XP');
set local role authenticated;
select public.craft_item('oak_plank',version,gen_random_uuid()) from craft_fixture;
select throws_ok($$select public.craft_item('oak_plank',version,gen_random_uuid()) from craft_fixture$$,'P0001','INSUFFICIENT_MATERIALS','Too few logs rejects crafting');
select is(public.list_crafting_recipes()#>>'{0,ingredients,0,owned}','2','Insufficient materials never change stock');
select is(public.list_crafting_recipes()#>>'{0,output,owned}','2','Outputs stack together');
reset role;
select is((select quantity from private.item_stacks where character_id=(select b from craft_fixture) and item_id='oak_logs'),5::bigint,'Another captain inventory is untouched');
select is((select xp from private.character_skills where character_id=(select a from craft_fixture) and skill_id='crafting'),20::bigint,'Rejected crafting never awards XP');
update private.character_skills set xp=190 where character_id=(select b from craft_fixture) and skill_id='crafting';
select set_config('request.jwt.claims','{"sub":"a9940000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select public.craft_item('oak_plank',version,request) from craft_fixture;
select is(public.list_crafting_recipes()#>>'{0,ingredients,0,owned}','0','Exact-cost crafting leaves no logs');
select is((public.get_own_skills()->>'character_level')::integer,8,'Crafting level-up updates Character Level');
reset role;
select is((select count(*) from private.item_stacks where character_id=(select b from craft_fixture) and item_id='oak_logs'),0::bigint,'Empty stacks are deleted');
select is((select count(*) from private.crafting_requests where request_id=(select request from craft_fixture)),2::bigint,'Receipt UUID is isolated per character');
savepoint craft_combat;
update public.characters set energy=100 where id=(select b from craft_fixture);
set local role authenticated;
select public.start_combat(a,gen_random_uuid()) from craft_fixture;
select throws_ok($$select public.craft_item('oak_plank',version,gen_random_uuid()) from craft_fixture$$,'P0001','IN_COMBAT','Combat blocks new crafting');
select lives_ok($$select public.craft_item('oak_plank',version,request) from craft_fixture$$,'Old crafting can be checked during combat');
reset role;
rollback to savepoint craft_combat;
update public.characters set energy=100 where id=(select b from craft_fixture);
set local role authenticated;
select public.depart_harbor((public.get_game_state()#>>'{sea,version}')::uuid,gen_random_uuid());
select throws_ok($$select public.craft_item('oak_plank',version,gen_random_uuid()) from craft_fixture$$,'P0001','NOT_IN_HARBOR','Travel blocks new crafting');
select lives_ok($$select public.craft_item('oak_plank',version,request) from craft_fixture$$,'Old crafting can be checked while traveling');
reset role;
select set_config('request.jwt.claims','{"sub":"a9940000-0000-4000-8000-000000000001","role":"authenticated"}',true);
update public.characters set crew_health=0 where id=(select a from craft_fixture);
set local role authenticated;
select throws_ok($$select public.craft_item('oak_plank',version,gen_random_uuid()) from craft_fixture$$,'P0001','IN_HOSPITAL','Hospital blocks new crafting');
select lives_ok($$select public.craft_item('oak_plank',version,request) from craft_fixture$$,'Old crafting can be checked in hospital');
reset role;
update public.characters set hospital_started_at=null,hospital_until=null,crew_health=100 where id=(select a from craft_fixture);
update private.item_stacks set quantity=5 where character_id=(select a from craft_fixture) and item_id='oak_logs';
update private.character_skills set xp=9007199254740986 where character_id=(select a from craft_fixture) and skill_id='crafting';
set local role authenticated;
select throws_ok($$select public.craft_item('oak_plank',version,gen_random_uuid()) from craft_fixture$$,'P0001','SKILL_XP_LIMIT','Crafting rejects a partial XP award at the storage limit');
reset role;
select is((select quantity from private.item_stacks where character_id=(select a from craft_fixture) and item_id='oak_logs'),5::bigint,'XP limit preserves ingredients');
select * from finish();
rollback;
