begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select is((select loot_table_id from private.activity_loot where activity_id='woodland_logging'),'woodland_logging','Logging uses the woodland loot table');
select is((select count(*) from private.loot_entries where loot_table_id='woodland_logging'),1::bigint,'Logging table contains only one item');
select is((select item_id from private.loot_entries where loot_table_id='woodland_logging'),'oak_logs','The sole reward is Oak Logs');
select is((select quantity from private.loot_entries where loot_table_id='woodland_logging'),1,'A success grants one log');
select ok((select bool_and(d.item_id='oak_logs' and d.chance=100) from generate_series(1,100) l cross join lateral private.loot_distribution('woodland_logging',l,100) d),'Every successful attempt gives Oak Logs at every level');
select is((select success_start from private.activity_loot where activity_id='woodland_logging'),70::numeric,'Logging starts at seventy percent success');
select is((select success_end from private.activity_loot where activity_id='woodland_logging'),90::numeric,'Logging reaches ninety percent success');
select is((select mastery_level from private.activity_loot where activity_id='woodland_logging'),100,'Logging reaches mastery at level one hundred');
insert into auth.users(id,email,is_anonymous,raw_user_meta_data) values
('a9950000-0000-4000-8000-000000000001','logging-loot@example.test',false,'{"character_name":"LoggingCaptain"}');
create temporary table logging_fixture as select id captain,gen_random_uuid() request from public.characters where user_id='a9950000-0000-4000-8000-000000000001';
create temporary table logging_results(key text primary key,value jsonb);
grant select on logging_fixture to authenticated;
grant all on logging_results to authenticated;
update public.characters set stamina=20,stamina_updated_at=clock_timestamp()+interval '1 day' where id=(select captain from logging_fixture);
-- Make success deterministic within this rolled-back fixture.
update private.activity_loot set success_start=100,success_end=100 where activity_id='woodland_logging';
select set_config('request.jwt.claims','{"sub":"a9950000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
insert into logging_results select 'first',public.perform_activity('woodland_logging',1,10,request) from logging_fixture;
select is((select value#>>'{loot,item_id}' from logging_results where key='first'),'oak_logs','Logging grants logs through the actual activity command');
select is((select value#>>'{loot,quantity}' from logging_results where key='first'),'1','Receipt captures one log');
select is((select value->>'xp_awarded' from logging_results where key='first'),'10','Logging keeps its XP reward');
select is((select public.perform_activity('woodland_logging',1,10,request) from logging_fixture),(select value from logging_results where key='first'),'Retry keeps the original log receipt');
select public.perform_activity('woodland_logging',1,10,gen_random_uuid()) from generate_series(1,4);
select is(public.list_crafting_recipes()#>>'{0,ingredients,0,owned}','5','Five successful logging attempts supply the crafting recipe');
select is((public.get_game_state()->>'stamina')::integer,15,'Five unique attempts spend five Stamina');
insert into logging_results select 'craft',public.craft_item('oak_plank',public.list_crafting_recipes()#>>'{0,version}',gen_random_uuid());
select is(public.list_crafting_recipes()#>>'{0,ingredients,0,owned}','0','Crafting consumes all five gathered logs');
select is(public.list_crafting_recipes()#>>'{0,output,owned}','1','Gathered logs become one existing Oak Plank');
reset role;
update private.activity_loot set success_start=0,success_end=0 where activity_id='woodland_logging';
set local role authenticated;
insert into logging_results select 'miss',public.perform_activity('woodland_logging',1,10,gen_random_uuid());
select is((select value#>>'{loot,caught}' from logging_results where key='miss'),'false','A failed logging attempt awards no item');
select is(public.list_crafting_recipes()#>>'{0,ingredients,0,owned}','0','The fixed loot entry does not bypass the success roll');
reset role;
select * from finish();
rollback;
