begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
update private.player_statistics_config set activity_tracked_since=statement_timestamp()-interval '45 days';
insert into auth.users(id,email,is_anonymous,created_at,raw_user_meta_data) values
('ac220000-0000-4000-8000-000000000001','statistics-admin@example.test',false,statement_timestamp()-interval '3 days','{"character_name":"StatisticsAdmin"}'),
('ac220000-0000-4000-8000-000000000002','statistics-player@example.test',false,statement_timestamp()-interval '10 days','{"character_name":"StatisticsPlayer","is_admin":true}'),
('ac220000-0000-4000-8000-000000000003','statistics-old@example.test',false,statement_timestamp()-interval '600 days','{"character_name":"StatisticsOlder"}'),
('ac220000-0000-4000-8000-000000000004','statistics-anonymous@example.test',true,statement_timestamp(),'{}');
insert into private.admin_members(user_id) values('ac220000-0000-4000-8000-000000000001');
create temp table saved(key text primary key,value jsonb);
grant all on saved to authenticated;
select is((select count(*) from private.player_statistics_accounts where user_id::text like 'ac220000-%'),3::bigint,'Only registered accounts enter statistics');
select ok((select bool_and(relrowsecurity) from pg_class where oid in('private.player_statistics_accounts'::regclass,'private.player_activity_daily'::regclass,'private.player_statistics_config'::regclass)),'Analytics tables use RLS');
set local role anon;
select throws_ok($$select public.admin_player_statistics()$$,'42501',null,'Anonymous statistics access denied');
select throws_ok($$select public.admin_players()$$,'42501',null,'Anonymous directory access denied');
select throws_ok($$select public.record_player_activity()$$,'42501',null,'Anonymous activity submission denied');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"ac220000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select public.admin_player_statistics()$$,'42501','ADMIN_REQUIRED','Metadata cannot grant analytics access');
select throws_ok($$select public.admin_players()$$,'42501','ADMIN_REQUIRED','Player directory requires admin membership');
select throws_ok($$select * from private.player_statistics_accounts$$,'42501',null,'Private account timestamps cannot be read directly');
select throws_ok($$select * from private.player_activity_daily$$,'42501',null,'Raw daily activity stays private');
select throws_ok($$select private.track_player_statistics()$$,'42501',null,'Clients cannot invoke tracking');
select set_config('request.jwt.claims','{"sub":"ac220000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into saved select 'before',public.admin_player_statistics();
select is(public.admin_players('Statistics')->>'total','3','Directory finds registered characters');
select is(public.admin_players('Statistics',0,'newest')#>>'{rows,0,display_name}','StatisticsAdmin','Newest registration sorts first');
select is(public.admin_players('Statistics',0,'oldest')#>>'{rows,0,display_name}','StatisticsOlder','Oldest registration sorts first');
select is(public.admin_players('Statistics',0,'newest','never')->>'total','3','No sign-in is represented explicitly');
select is(public.admin_players('Statistics',2147483647)->>'page','0','Oversized page clamps to the last available page');
select is(public.admin_players('missing-user')->>'total','0','Empty search is well-defined');
select throws_ok($$select public.admin_players('',0,'bad')$$,'22023','INVALID_PLAYER_FILTER','Invalid directory sort is rejected');
select throws_ok($$select public.admin_players('',0,'name','bad')$$,'22023','INVALID_PLAYER_FILTER','Invalid activity filter is rejected');
select throws_ok($$select public.admin_player_statistics('bad')$$,'22023','INVALID_PLAYER_PERIOD','Invalid history period is rejected');
select throws_ok($$select public.admin_player_statistics(null)$$,'22023','INVALID_PLAYER_PERIOD','Null history period is rejected');
reset role;
update auth.users set last_sign_in_at=date_trunc('day',statement_timestamp() at time zone 'UTC') at time zone 'UTC' where id='ac220000-0000-4000-8000-000000000002';
update auth.users set last_sign_in_at=statement_timestamp() where id='ac220000-0000-4000-8000-000000000002';
update auth.users set last_sign_in_at=last_sign_in_at,raw_user_meta_data=raw_user_meta_data||'{"test":true}' where id='ac220000-0000-4000-8000-000000000002';
select is((select count(*) from private.player_activity_daily d join private.player_statistics_accounts a on a.id=d.account_id where a.user_id='ac220000-0000-4000-8000-000000000002' ),1::bigint,'Repeated sign-ins create one active account per UTC day');
select is((select count(distinct account_id) from private.player_activity_daily d join private.player_statistics_accounts a on a.id=d.account_id where a.user_id='ac220000-0000-4000-8000-000000000002'),1::bigint,'Repeat sign-ins have one distinct account');
update auth.users set last_sign_in_at=statement_timestamp()-interval '40 days' where id='ac220000-0000-4000-8000-000000000003';
insert into private.player_activity_daily(account_id,day,first_at,last_at)
select id,(statement_timestamp() at time zone 'UTC')::date-1,statement_timestamp()-interval '1 day',statement_timestamp()-interval '1 day'
from private.player_statistics_accounts where user_id='ac220000-0000-4000-8000-000000000002' on conflict do nothing;
update private.player_statistics_accounts set last_active_at=statement_timestamp()-interval '1 hour' where user_id='ac220000-0000-4000-8000-000000000002';
insert into auth.sessions(id,user_id,created_at,updated_at) values('ac220000-0000-4000-8000-000000000099','ac220000-0000-4000-8000-000000000002',statement_timestamp(),statement_timestamp());
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"ac220000-0000-4000-8000-000000000002","role":"authenticated","session_id":"ac220000-0000-4000-8000-000000000099"}',true);
select lives_ok($$select public.record_player_activity()$$,'An existing signed-in session records activity');
select lives_ok($$select public.record_player_activity()$$,'Repeated session checks are harmless');
reset role;
select ok((select last_active_at>statement_timestamp()-interval '1 minute' from private.player_statistics_accounts where user_id='ac220000-0000-4000-8000-000000000002'),'Server time updates latest activity');
select is((select last_sign_in_at from auth.users where id='ac220000-0000-4000-8000-000000000002'),(select last_sign_in_at from private.player_statistics_accounts where user_id='ac220000-0000-4000-8000-000000000002'),'Session activity does not fabricate a fresh login');
select is((select count(*) from private.player_activity_daily d join private.player_statistics_accounts a on a.id=d.account_id where a.user_id='ac220000-0000-4000-8000-000000000002' and day=(statement_timestamp() at time zone 'UTC')::date),1::bigint,'Duplicate activity shares the same daily row');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"ac220000-0000-4000-8000-000000000003","role":"authenticated","session_id":"ac220000-0000-4000-8000-000000000099"}',true);
select throws_ok($$select public.record_player_activity()$$,'42501','UNAUTHORIZED','Another account cannot reuse the session');
select set_config('request.jwt.claims','{"sub":"ac220000-0000-4000-8000-000000000001","role":"authenticated"}',true);

set local role authenticated;
insert into saved select 'after',public.admin_player_statistics();
select is((select (value#>>'{totals,active_24h}')::bigint from saved where key='after')-(select (value#>>'{totals,active_24h}')::bigint from saved where key='before'),1::bigint,'Recent sign-in cards count distinct existing accounts');
select is((select (value#>>'{period_totals,unique_active}')::bigint from saved where key='after')-(select (value#>>'{period_totals,unique_active}')::bigint from saved where key='before'),1::bigint,'Repeat logins and session activity count once in the whole period');
select is(public.admin_players('Statistics',0,'last_active')#>>'{rows,0,display_name}','StatisticsPlayer','Latest activity sorts first');
select is(public.admin_players('Statistics',0,'newest','24h')->>'total','1','Recent filter uses activity timestamp');
select is(public.admin_players('Statistics',0,'newest','inactive')->>'total','2','Inactive filter includes old and never-signed-in accounts');
select is(jsonb_array_length(public.admin_player_statistics('1m')->'history'),(statement_timestamp() at time zone 'UTC')::date-((statement_timestamp() at time zone 'UTC')::date-interval '1 month')::date,'Last-month chart includes today and one month of UTC dates');
select is(jsonb_array_length(public.admin_player_statistics('12m')->'history'),(statement_timestamp() at time zone 'UTC')::date-((statement_timestamp() at time zone 'UTC')::date-interval '12 months')::date,'Twelve-month chart handles leap-year length');
select ok(jsonb_array_length(public.admin_player_statistics('all')->'history')<=500,'All-time history includes all dates with bounded buckets');
select ok((public.admin_player_statistics('all')->>'bucket_days')::integer>1,'Long all-time history groups into clearly labelled intervals');
select ok((public.admin_player_statistics('all')#>>'{history,0,at}')::timestamptz<=statement_timestamp()-interval '600 days','All-time reaches the oldest registration');
select is(public.admin_player_statistics('12m')#>>'{history,0,unique_players}',null,'Days before tracking are unknown rather than zero');
select is(public.admin_player_statistics('1m')->'history'->-1->>'accounts',public.admin_player_statistics()#>>'{totals,accounts}','Growth chart ends at current account count');
select ok(not (public.admin_player_statistics()::text ~ '(email|user_id|password|token|ip_address)'),'Aggregate statistics expose no personal or authentication payload');
reset role;
create temp table removed_id as select id from private.player_statistics_accounts where user_id='ac220000-0000-4000-8000-000000000002';
delete from auth.users where id='ac220000-0000-4000-8000-000000000002';
select is((select user_id from private.player_statistics_accounts where id=(select id from removed_id)),null::uuid,'Hard deletion removes the link to the auth identifier');
select ok((select deleted_at is not null from private.player_statistics_accounts where id=(select id from removed_id)),'Account removal timestamp is retained');
select ok((select count(*)>0 from private.player_activity_daily where account_id=(select id from removed_id)),'Removal preserves unique activity history');
select is((private.admin_player_statistics()#>>'{totals,accounts}')::bigint,(select (value#>>'{totals,accounts}')::bigint-1 from saved where key='after'),'Removed accounts leave current totals');
select is((private.admin_player_statistics()#>>'{period_totals,new_accounts}'),(select value#>>'{period_totals,new_accounts}' from saved where key='after'),'Removal does not rewrite registration history');
select is((private.admin_player_statistics()#>>'{period_totals,removed_accounts}')::bigint,(select (value#>>'{period_totals,removed_accounts}')::bigint+1 from saved where key='after'),'Removal increments period count');
select is(private.admin_player_statistics()->'history'->-1->>'accounts',private.admin_player_statistics()#>>'{totals,accounts}','Growth includes account removal');
update auth.users set deleted_at=statement_timestamp() where id='ac220000-0000-4000-8000-000000000003';
select is(private.admin_players('Statistics')->>'total','1','Soft-deleted accounts are excluded from the directory');
delete from private.admin_members where user_id='ac220000-0000-4000-8000-000000000001';
set local role authenticated;
select throws_ok($$select public.admin_player_statistics()$$,'42501','ADMIN_REQUIRED','Revocation immediately blocks statistics');
select throws_ok($$select public.admin_players()$$,'42501','ADMIN_REQUIRED','Revocation immediately blocks directory access');
reset role;
select * from finish();
rollback;
