begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,is_anonymous,raw_user_meta_data) values
('d7400000-0000-4000-8000-000000000001','ship-materials@example.test',false,'{"character_name":"MaterialCaptain"}');
create temporary table material_fixture as select id captain,gen_random_uuid() request from public.characters where user_id='d7400000-0000-4000-8000-000000000001';
grant select on material_fixture to authenticated;
create temporary table material_receipts(value jsonb);
grant all on material_receipts to authenticated;
update public.characters set energy_updated_at=clock_timestamp()+interval '1 day' where id=(select captain from material_fixture);
select is(private.ship_training_gain(10,1,5),2.012938::numeric,'Ship multiplier is applied to every Energy unit');
select is(private.ship_training_gain(10,1,6)+private.ship_training_gain(10+private.ship_training_gain(10,1,6),1,7),
  private.ship_training_gain(10,1,13),'Ship gain is independent of job partitioning');
select ok((select stackable and active and tradable and category_id='materials' from private.item_definitions where id='iron_nails'),'Iron Nails are active tradable stackable materials');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"d7400000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select private.ship_material_costs(null,5)$$,'42501',null,'Other player inventory cannot be read through internal cost helper');
select throws_ok($$select private.ship_training_gain(10,1,5)$$,'42501',null,'Internal ship gain is not exposed');
select is(jsonb_array_length(public.get_game_state()#>'{training,ship_materials}'),2,'Owner receives both required materials');
select throws_ok($$select public.start_ship_upgrade('attack',5,'ship_1',gen_random_uuid())$$,'P0001','INSUFFICIENT_MATERIALS','No materials rejects the job');
select is(public.get_game_state()->>'energy','100','Missing materials preserve Energy');
reset role;
insert into private.item_stacks(character_id,item_id,quantity) select captain,'oak_planks',10 from material_fixture;
set local role authenticated;
select throws_ok($$select public.start_ship_upgrade('attack',6,'ship_1',gen_random_uuid())$$,'P0001','INSUFFICIENT_MATERIALS','Both ingredients are required');
reset role;
select is((select quantity from private.item_stacks where character_id=(select captain from material_fixture) and item_id='oak_planks'),10::bigint,'Failed job does not partially consume planks');
select is((select count(*) from private.training_requests where character_id=(select captain from material_fixture)),0::bigint,'Failed jobs do not save a successful receipt');
insert into private.item_stacks(character_id,item_id,quantity) select captain,'iron_nails',2 from material_fixture;
update private.item_definitions set active=false where id='iron_nails';
set local role authenticated;
select throws_ok($$select public.start_ship_upgrade('attack',6,'ship_1',gen_random_uuid())$$,'P0001','MATERIAL_UNAVAILABLE','Inactive materials cannot fund work');
reset role;
update private.item_definitions set active=true where id='iron_nails';
update public.characters set energy=4 where id=(select captain from material_fixture);
set local role authenticated;
select throws_ok($$select public.start_ship_upgrade('attack',6,'ship_1',gen_random_uuid())$$,'P0001','NOT_ENOUGH_ENERGY','Insufficient Energy rejects funded material order');
reset role;
select is((select quantity from private.item_stacks where character_id=(select captain from material_fixture) and item_id='iron_nails'),2::bigint,'Insufficient Energy preserves materials');
update public.characters set energy=100 where id=(select captain from material_fixture);
create temporary table material_circulation_before as select item_id,total from private.item_circulation where item_id in ('oak_planks','iron_nails');
set local role authenticated;
insert into material_receipts select public.start_ship_upgrade('attack',6,'ship_1',request) from material_fixture;
select is(public.get_game_state()->>'energy','94','Successful job pays Energy once');
select is(public.get_game_state()#>>'{training,ship_job,stat_gain}','2.415814','Successful job snapshots multiplied reward');
select is(public.get_game_state()#>>'{training,ship_job,xp_gain}','6','XP is not tripled');
select is((select value#>>'{materials,0,quantity}' from material_receipts),'2','Six Energy rounds up to two Iron Nails');
select is((select value#>>'{materials,1,quantity}' from material_receipts),'2','Six Energy rounds up to two Oak Planks');
select is((select public.start_ship_upgrade('attack',6,'ship_1',request) from material_fixture),(select value from material_receipts),'Retry returns original paid-material snapshot even with no nails remaining');
select throws_ok($$select public.start_ship_upgrade('defense',5,'ship_1',gen_random_uuid())$$,'P0001','SHIP_WORK_ACTIVE','Only one active job is allowed');
select throws_ok($$select public.start_ship_upgrade('attack',7,'ship_1',request) from material_fixture$$,'22023','REQUEST_CONFLICT','Changed cost cannot reuse a receipt');
reset role;
select is((select quantity from private.item_stacks where character_id=(select captain from material_fixture) and item_id='oak_planks'),8::bigint,'Retry does not consume more planks');
select is((select count(*) from private.item_stacks where character_id=(select captain from material_fixture) and item_id='iron_nails'),0::bigint,'Exact material depletion removes empty stack');
select ok((select bool_and(c.total=b.total-2) from private.item_circulation c join material_circulation_before b using(item_id)),'Both circulation counters decrease by the consumed amount');
select is((select extract(epoch from(finishes_at-started_at)) from private.ship_upgrade_jobs where character_id=(select captain from material_fixture)),36::numeric,'Work still takes six seconds per Energy');
update private.ship_upgrade_jobs set started_at=clock_timestamp()-interval '1 minute',finishes_at=clock_timestamp()-interval '1 second' where character_id=(select captain from material_fixture);
set local role authenticated;
select is(public.get_game_state()->>'ship_attack','12.415814','Completion awards the stored stat gain');
select is(public.get_game_state()#>>'{training,last_ship_job,materials,0,quantity}','2','Completed work retains its material receipt');
select is((select public.start_ship_upgrade('attack',6,'ship_1',request) from material_fixture),(select value from material_receipts),'Completed job retry never starts another job');
select is(public.get_game_state()->>'energy','94','Completed job retry does not spend Energy');
select * from finish();
rollback;
