import type { PlayerSearchPage } from "@/lib/player-identity";
import type { ItemHistory, ItemHistoryPeriod } from "@/lib/item-history";
import type { MarketItem, MarketListing, MarketPage, MarketReceipt, SaleEntry } from "@/lib/marketplace";
import type { AdminResource, AdminPage, AdminPayload, AdminReceipt } from "@/lib/admin";
import type { CirculationHistory, CirculationPeriod } from "@/lib/circulation";
import type { InventoryEntryType, InventoryPage, TrashReceipt } from "@/lib/inventory";
import type { EquipSlot, EquipReceipt } from "@/lib/equipment";
import type { TavernReceipt } from "@/lib/morale";
import type { TrainingReceipt } from "@/lib/training";
import type { HospitalPatient, HospitalRoster, HospitalStatus } from "@/lib/hospital";
import type { BankDirection, BankTransfer } from "@/lib/bank";
import type { HarborPlayer, HarborRoster } from "@/lib/harbor";
import type { GameState, TrainingGroup, Stat } from "@/lib/game";
import type { AttackLock, CombatLog, Battle, CombatPreview, CombatResponse, CombatError, DefenceOrder, CombatOrder } from "@/lib/combat";

import type { ScoutReceipt, ScoutPage } from "@/lib/sea-scouting";
import type { CharacterStatus, TravelReceipt } from "@/lib/sea-travel";
import type { NavigationLock } from "@/lib/game-navigation";

export type Character = {
  id: string;
  user_id: string;
  player_number: number;
  display_name: string;
  name_key: string;
  location: "the_harbor" | "open_sea" | "traveling";
  sea_step: number;
  max_sea_distance: number;
  sea_version: string;
  sea_visit_id: string | null;
  sea_place_id: string | null;
  sea_place_name: string | null;
  travel_id: string | null;
  travel_kind: "depart" | "onward" | "return" | null;
  travel_target_step: number | null;
  travel_place_id: string | null;
  travel_place_name: string | null;
  travel_started_at: string | null;
  travel_arrives_at: string | null;
  created_at: string;
  stamina: number;
  stamina_updated_at: string;
  energy_updated_at: string;
  morale_updated_at: string;
  crew_morale: number;
  ship_recovery_at: string;
  crew_recovery_at: string;
  hospital_started_at: string | null;
  hospital_until: string | null;
  energy: number;
  gold_coins: number;
  bank_gold_coins: number;
  ship_health: number;
  crew_health: number;
  defence_order: DefenceOrder;
  protected_until: string | null;
} & Record<`${TrainingGroup}_${Stat}`, number>;

export type CharacterProfile = { character_id: string; character_level: number } & Pick<Character, "player_number" | "display_name" | "location" | "created_at">;

export type Database = {
  public: {
    Tables: {
      market_item_events: { Row: { item_id: string; revision: number }; Insert: never; Update: never; Relationships: [] };
      hospital_patients: { Row: Omit<HospitalPatient, "player_number">; Insert: never; Update: never; Relationships: [] };
      player_game_events: { Row: { character_id: string; revision: number }; Insert: never; Update: never; Relationships: [] };
      character_profiles: { Row: CharacterProfile & { max_sea_distance: number; arrival_max_sea_distance: number | null; arrives_at: string | null; arrival_location: "the_harbor" | "open_sea" | null }; Insert: never; Update: never; Relationships: [] };
      harbor_players: { Row: Omit<HarborPlayer, "player_number"> & { arrives_at: string | null }; Insert: never; Update: never; Relationships: [] };
      characters: {
        Row: Character;
        Insert: { display_name: string };
        Update: never;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_player_context: { Args: Record<string, never>; Returns: { character: Character | null; is_admin: boolean; config_revision: string } | null };
      get_player_snapshot: { Args: Record<string, never>; Returns: { state: GameState; skills: import("@/lib/skills").SkillProgress; notifications: import("@/lib/notifications").NotificationSummary; messages: import("@/lib/messages").MessageSummary } | null };
      get_message_summary: { Args: Record<string, never>; Returns: import("@/lib/messages").MessageSummary };
      get_mail_summary: { Args: Record<string, never>; Returns: import("@/lib/messages").MailSummary };
      get_mailbox: { Args: { folder?: import("@/lib/messages").MailFolder; query?: string; page?: number }; Returns: import("@/lib/messages").MailPage };
      get_mail: { Args: { mail_id: string; include_history?: boolean }; Returns: import("@/lib/messages").MailDetail };
      get_mail_ignored: { Args: Record<string, never>; Returns: import("@/lib/messages").MailPerson[] };
      send_mail: { Args: { target_numbers: number[]; mail_subject: string; mail_body: string; request_id: string; reply_to_id?: string }; Returns: import("@/lib/messages").MailReceipt };
      update_mail: { Args: { mail_ids: string[]; operation: import("@/lib/messages").MailOperation }; Returns: undefined };
      set_mail_ignored: { Args: { target_player_number: number; ignored: boolean }; Returns: undefined };
      get_notification_summary: { Args: Record<string, never>; Returns: import("@/lib/notifications").NotificationSummary };
      get_notifications: { Args: { before_id?: string }; Returns: import("@/lib/notifications").NotificationPage };
      get_forum_index: { Args: Record<string, never>; Returns: import("@/lib/forums").ForumIndex };
      get_forum_board: { Args: { board_id: string; page?: number }; Returns: import("@/lib/forums").ForumBoardPage };
      get_forum_thread: { Args: { thread_id: string; page?: number }; Returns: import("@/lib/forums").ForumThreadPage };
      locate_forum_post: { Args: { post_id?: string; thread_id?: string }; Returns: import("@/lib/forums").ForumLocation };
      get_forum_post_history: { Args: { post_id: string }; Returns: import("@/lib/forums").ForumPostHistory };
      create_forum_thread: { Args: { board_id: string; thread_title: string; post_body: string; request_id: string }; Returns: import("@/lib/forums").ForumReceipt };
      create_forum_post: { Args: { thread_id: string; post_body: string; quoted_post_id: string | null; request_id: string }; Returns: import("@/lib/forums").ForumReceipt };
      edit_forum_post: { Args: { post_id: string; post_body: string; thread_title: string | null; expected_edit_count: number }; Returns: import("@/lib/forums").ForumEditReceipt };
      withdraw_forum_post: { Args: { post_id: string }; Returns: import("@/lib/forums").ForumWithdrawReceipt };
      mark_forum_thread_read: { Args: { thread_id: string; through_number: number }; Returns: undefined };
      mark_forum_board_read: { Args: { board_id?: string }; Returns: undefined };
      set_forum_reaction: { Args: { post_id: string; reaction: import("@/lib/forums").ForumReaction }; Returns: import("@/lib/forums").ForumReactionReceipt };
      set_forum_subscription: { Args: { thread_id: string; subscribed: boolean }; Returns: undefined };
      search_forums: { Args: { query: string; author?: string | null; board_id?: string | null; threads_only?: boolean; page?: number }; Returns: import("@/lib/forums").ForumSearchPage };
      get_forum_subscriptions: { Args: { page?: number }; Returns: import("@/lib/forums").ForumSubscriptionPage };
      get_forum_author_stats: { Args: { player_number: number }; Returns: import("@/lib/forums").ForumAuthorStats };
      moderate_forum: { Args: { action: import("@/lib/forums").ForumModerationAction; payload: Record<string, string>; request_id: string; reason: string }; Returns: import("@/lib/forums").ForumModerationReceipt };
      mark_notification_read: { Args: { notification_id: string }; Returns: undefined };
      mark_all_notifications_read: { Args: { through_id: string }; Returns: undefined };
      list_crafting_recipes: { Args: Record<string, never>; Returns: import("@/lib/crafting").CraftingRecipe[] };
      craft_item: { Args: { recipe_id: string; expected_version: string; request_id: string }; Returns: import("@/lib/crafting").CraftingReceipt };
      perform_activity: { Args: { activity_id: string; expected_stamina_cost: number; expected_xp_gain: number; request_id: string }; Returns: import("@/lib/activities").ActivityReceipt };
      get_own_skills: { Args: Record<string, never>; Returns: import("@/lib/skills").SkillProgress | null };
      search_players: { Args: { search_term?: string; requested_page?: number }; Returns: PlayerSearchPage };
      list_market_items: { Args: { category_id?: string; search_term?: string; requested_page?: number }; Returns: MarketPage<MarketItem> };
      list_market_listings: { Args: { target_item?: string; own_only?: boolean; requested_page?: number }; Returns: MarketPage<MarketListing> };
      list_market_inventory: { Args: { category_id?: string; search_term?: string; requested_page?: number }; Returns: InventoryPage };
      create_market_listings: { Args: { entries: SaleEntry[]; request_id: string }; Returns: MarketReceipt };
      buy_market_listing: { Args: { listing_id: string; quantity: number; expected_unit_price: number; request_id: string }; Returns: MarketReceipt };
      cancel_market_listing: { Args: { listing_id: string; request_id: string }; Returns: MarketReceipt };
      scout_nearby_ships: { Args: { expected_version: string; request_id: string }; Returns: ScoutReceipt };
      get_sea_scout: { Args: { requested_page?: number }; Returns: ScoutPage | null };
      depart_harbor: { Args: { expected_version: string; request_id: string }; Returns: TravelReceipt };
      choose_sea_route: { Args: { expected_version: string; option_id: string; request_id: string }; Returns: TravelReceipt };
      return_to_harbor: { Args: { expected_version: string; request_id: string }; Returns: TravelReceipt };
      get_character_status: { Args: { target_id: string }; Returns: CharacterStatus | null };
      is_admin: { Args: Record<string, never>; Returns: boolean };
      admin_get_loot_table: { Args: { target_id: string }; Returns: import("@/lib/loot").LootTable | null };
      admin_catalog: { Args: Record<string, never>; Returns: AdminResource[] };
      admin_economy: { Args: { period?: import("@/lib/economy").EconomyPeriod; item_search?: string; item_page?: number; item_sort?: import("@/lib/economy").EconomySort }; Returns: import("@/lib/economy").EconomyDashboard };
      record_player_presence: { Args: { tab_id: string; is_active: boolean; page_action?: boolean; closed?: boolean }; Returns: undefined };
      record_player_activity: { Args: Record<string, never>; Returns: undefined };
      admin_player_statistics: { Args: { period?: import("@/lib/player-statistics").PlayerPeriod }; Returns: import("@/lib/player-statistics").PlayerStatistics };
      admin_players: { Args: { search_term?: string; requested_page?: number; sort_by?: import("@/lib/player-statistics").PlayerSort; activity?: import("@/lib/player-statistics").PlayerActivityFilter }; Returns: import("@/lib/player-statistics").AdminPlayerList };
      admin_overview: { Args: Record<string, never>; Returns: Record<string, string> };
      admin_read: { Args: { resource: string; search_term?: string; requested_page?: number; filters?: Record<string, string | null> }; Returns: AdminPage };
      admin_mutate: { Args: { action: string; payload: AdminPayload; request_id: string; reason: string }; Returns: AdminReceipt };
      get_item_market_value: { Args: { target_item: string; period?: ItemHistoryPeriod }; Returns: ItemHistory };
      get_item_circulation: { Args: { target_item: string; period?: CirculationPeriod }; Returns: CirculationHistory };
      list_inventory: { Args: { category_id?: string; search_term?: string; requested_page?: number }; Returns: InventoryPage };
      trash_inventory_item: { Args: { entry_id: string; entry_type: InventoryEntryType; quantity: number; request_id: string }; Returns: TrashReceipt };
      equip_item: { Args: { entry_id: string; request_id: string }; Returns: EquipReceipt };
      unequip_item: { Args: { equipment_slot: EquipSlot; request_id: string }; Returns: EquipReceipt };
      get_gameplay_revision: { Args: Record<string, never>; Returns: string };
      list_harbor_players: { Args: { requested_page?: number }; Returns: HarborRoster };
      is_character_name_available: { Args: { candidate: string }; Returns: boolean };
      list_hospital_patients: { Args: { requested_page?: number }; Returns: HospitalRoster };
      get_hospital_status: { Args: { target_id: string }; Returns: HospitalStatus };
      get_navigation_lock: { Args: Record<string, never>; Returns: NavigationLock };
      get_attack_lock: { Args: Record<string, never>; Returns: AttackLock | null };
      get_combat_log: { Args: { battle_id: string }; Returns: CombatLog | null };
      get_game_state: { Args: Record<string, never>; Returns: GameState | null };
      buy_tavern_meal: { Args: { expected_gold_cost: number; expected_morale_gain: number; request_id: string }; Returns: TavernReceipt };
      transfer_gold: { Args: { direction: BankDirection; amount: number; request_id: string }; Returns: BankTransfer };
      train_crew: { Args: { stat: Stat; expected_tier_id: string; request_id: string }; Returns: TrainingReceipt };
      start_ship_upgrade: { Args: { stat: Stat; energy_amount: number; expected_workshop_id: string; request_id: string }; Returns: TrainingReceipt };
      purchase_training_tier: { Args: { training_group: TrainingGroup; tier_id: string; request_id: string }; Returns: TrainingReceipt };
      get_combat_preview: { Args: { target_id: string }; Returns: CombatPreview | CombatError };
      start_combat: { Args: { target_id: string; request_id: string }; Returns: CombatResponse };
      get_combat: { Args: { battle_id: string }; Returns: Battle | null };
      submit_combat_order: { Args: { battle_id: string; expected_round: number; player_order: CombatOrder; request_id: string }; Returns: CombatResponse };
      save_defence_orders: { Args: { preset: DefenceOrder }; Returns: { preset: DefenceOrder } };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
