import type gameplay from "../../config/gameplay.json";
import type auth from "../../config/auth.json";
import type frontend from "../../config/frontend.json";
import type server from "../../config/server.json";
import type testing from "../../config/testing.json";
export type Configuration = { gameplay: typeof gameplay; auth: typeof auth; frontend: typeof frontend; server: typeof server; testing: typeof testing };
export const root: string;
export const names: string[];
export function read(path: string): string;
export function loadConfig(): Configuration;
export function validateConfig(config: unknown): asserts config is Configuration;
export function pathValue(object: unknown, path: string): string | number | boolean;
export function render(template: string, config: unknown, mode?: string): string;
export function localOrigin(config: Configuration, test?: boolean): string;
export function gameplaySql(config: Configuration): string;
export function revision(config: Configuration): string;
export function migrationSql(config: Configuration): string;
export function latestConfigMigration(): string | undefined;
export function generatedFiles(config: Configuration): Record<string, string>;
