{{include.training}}
{{include.resources}}
{{include.sea-scouting}}
{{include.sea-travel}}
{{include.combat}}
{{include.game-state}}
{{include.bank}}
{{include.hospital}}
{{include.combat-report}}
{{include.profile}}
{{include.circulation-tracking}}
{{include.market-value-tracking}}
{{include.market-value-history}}
{{include.inventory}}
{{include.circulation-history}}
{{include.marketplace-read}}
{{include.marketplace-sell}}
{{include.marketplace-buy}}
