{{include.training}}
{{include.resources}}
{{include.combat}}
{{include.game-state}}
{{include.bank}}
{{include.hospital}}
{{include.combat-report}}
{{include.profile}}
{{include.circulation-tracking}}
{{include.inventory}}
{{include.circulation-history}}
