{{include.skills}}
{{include.stamina}}
{{include.morale}}
{{include.training}}
{{include.resources}}
{{include.sea-scouting}}
{{include.sea-travel}}
{{include.combat}}
{{include.game-state}}
{{include.bank}}
{{include.tavern}}
{{include.content-schema}}
{{include.activities}}
{{include.hospital}}
{{include.combat-report}}
{{include.player-directory}}
{{include.circulation-tracking}}
{{include.market-value-tracking}}
{{include.market-value-history}}
{{include.inventory}}
{{include.crafting}}
{{include.circulation-history}}
{{include.marketplace-read}}
{{include.marketplace-sell}}
{{include.marketplace-buy}}
{{include.loot}}
{{include.content-seed}}
{{include.admin}}
{{include.economy}}
{{include.player-statistics}}
{{include.presence}}
{{include.profile}}
{{include.notifications}}
{{include.legacy-mail}}
{{include.mail-schema}}
{{include.mail-send}}
{{include.mail-read}}
{{include.mail-actions}}
{{include.player-context}}
