-- Generated by npm run config:sync. Edit config/gameplay.json or supabase/templates/gameplay.sql.
-- gameplay-revision: 4697f396f8a440c4ef012c3662341b9579e03d04dcf404bfabbe11450d76782a


-- Tier IDs and positions are durable; balance values may change.
do $catalog$ begin if exists(select 1 from private.training_tiers old left join (values
('crew','crew_1',0,'Deck Drills',0,0,1),
('crew','crew_2',1,'Harbor Exercises',100,250,2),
('crew','crew_3',2,'Sailor Training',500,1000,4),
('crew','crew_4',3,'Veteran Drills',1500,4000,8),
('crew','crew_5',4,'Boarding Practice',4000,15000,20),
('crew','crew_6',5,'Officer Training',10000,50000,50),
('crew','crew_7',6,'Elite Exercises',20000,150000,125),
('crew','crew_8',7,'Master Drills',40000,500000,300),
('crew','crew_9',8,'Legendary Training',65000,1500000,750),
('crew','crew_10',9,'Admiral Exercises',100000,5000000,1500),
('ship','ship_1',0,'Deck Workbench',0,0,1),
('ship','ship_2',1,'Harbor Workshop',100,250,2),
('ship','ship_3',2,'Shipwright Workshop',500,1000,4),
('ship','ship_4',3,'Reinforced Workshop',1500,4000,8),
('ship','ship_5',4,'Advanced Workshop',4000,15000,20),
('ship','ship_6',5,'Master Shipwright',10000,50000,50),
('ship','ship_7',6,'Naval Workshop',20000,150000,125),
('ship','ship_8',7,'Grand Workshop',40000,500000,300),
('ship','ship_9',8,'Royal Dockworks',65000,1500000,750),
('ship','ship_10',9,'Admiral Dockworks',100000,5000000,1500)
) incoming(training_group,id,position,name,xp_required,gold_cost,stat_gain) using(training_group,id) where incoming.id is null or incoming.position<>old.position) then raise exception 'Existing tier IDs and positions must be preserved'; end if; end $catalog$;
insert into private.training_tiers(training_group,id,position,name,xp_required,gold_cost,stat_gain) values
('crew','crew_1',0,'Deck Drills',0,0,1),
('crew','crew_2',1,'Harbor Exercises',100,250,2),
('crew','crew_3',2,'Sailor Training',500,1000,4),
('crew','crew_4',3,'Veteran Drills',1500,4000,8),
('crew','crew_5',4,'Boarding Practice',4000,15000,20),
('crew','crew_6',5,'Officer Training',10000,50000,50),
('crew','crew_7',6,'Elite Exercises',20000,150000,125),
('crew','crew_8',7,'Master Drills',40000,500000,300),
('crew','crew_9',8,'Legendary Training',65000,1500000,750),
('crew','crew_10',9,'Admiral Exercises',100000,5000000,1500),
('ship','ship_1',0,'Deck Workbench',0,0,1),
('ship','ship_2',1,'Harbor Workshop',100,250,2),
('ship','ship_3',2,'Shipwright Workshop',500,1000,4),
('ship','ship_4',3,'Reinforced Workshop',1500,4000,8),
('ship','ship_5',4,'Advanced Workshop',4000,15000,20),
('ship','ship_6',5,'Master Shipwright',10000,50000,50),
('ship','ship_7',6,'Naval Workshop',20000,150000,125),
('ship','ship_8',7,'Grand Workshop',40000,500000,300),
('ship','ship_9',8,'Royal Dockworks',65000,1500000,750),
('ship','ship_10',9,'Admiral Dockworks',100000,5000000,1500)
on conflict(training_group,id) do update set name=excluded.name,xp_required=excluded.xp_required,gold_cost=excluded.gold_cost,stat_gain=excluded.stat_gain;


create or replace function private.initialize_training_progress()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into private.character_training(character_id,training_group,tier_id)
    select new.id,training_group,id from private.training_tiers where position=0;
  return new;
end;
$$;
revoke all on function private.initialize_training_progress() from public,anon,authenticated;
drop trigger if exists initialize_training_progress on public.characters;
create trigger initialize_training_progress after insert on public.characters
for each row execute function private.initialize_training_progress();
insert into private.character_training(character_id,training_group,tier_id)
  select c.id,t.training_group,t.id from public.characters c cross join private.training_tiers t where t.position=0
  on conflict(character_id,training_group) do nothing;

create or replace function private.notify_training(captain_id uuid)
returns void language sql volatile security invoker set search_path='' as $$
  insert into public.player_game_events(character_id,revision) values(captain_id,1)
    on conflict(character_id) do update set revision=player_game_events.revision+1;
$$;

-- Caller holds the character/combat locks. The caller's observation time also drives snapshots.
create or replace function private.settle_ship_upgrade(captain_id uuid, observed_at timestamptz)
returns void language plpgsql volatile security invoker set search_path='' as $$
declare job private.ship_upgrade_jobs%rowtype;
begin
  select * into job from private.ship_upgrade_jobs where character_id=captain_id and applied_at is null for update;
  if not found or job.finishes_at>observed_at then return; end if;
  execute format('update public.characters set %I=%I+$1 where id=$2','ship_'||job.stat,'ship_'||job.stat)
    using job.stat_gain,captain_id;
  update private.character_training set xp=xp+job.xp_gain where character_id=captain_id and training_group='ship';
  update private.ship_upgrade_jobs set applied_at=observed_at where id=job.id;
  perform private.notify_training(captain_id);
end;
$$;

create or replace function private.training_state(captain_id uuid)
returns jsonb language sql stable security invoker set search_path='' as $$
  select jsonb_build_object(
    'progress',(select jsonb_object_agg(training_group,jsonb_build_object('xp',xp,'tier_id',tier_id))
      from private.character_training where character_id=captain_id),
    'ship_job',(select to_jsonb(j)-'character_id'-'config_revision' from private.ship_upgrade_jobs j
      where character_id=captain_id and applied_at is null),
    'last_ship_job',(select to_jsonb(j)-'character_id'-'config_revision' from private.ship_upgrade_jobs j
      where character_id=captain_id and applied_at is not null order by finishes_at desc,id desc limit 1));
$$;

-- Deterministic resolver is internal only; callers cannot choose the random roll.
create or replace function private.crew_training_gain(base_gain bigint, roll double precision)
returns bigint language plpgsql immutable strict security invoker set search_path='' as $$
begin
  if base_gain<1 or roll<0 or roll>=1 then raise exception 'INVALID_TRAINING_ROLL' using errcode='22023'; end if;
  return base_gain * case when roll < 100 / 10000.0
    then 2 else 1 end;
end;
$$;

create or replace function private.training_action(action text,payload jsonb,request_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare
  viewer_id uuid:=private.combat_captain();
  captain public.characters%rowtype;
  progress private.character_training%rowtype;
  tier private.training_tiers%rowtype;
  current_tier private.training_tiers%rowtype;
  previous private.training_requests%rowtype;
  job private.ship_upgrade_jobs%rowtype;
  recovered record;
  group_name text:=case when action='crew' then 'crew' when action='ship' then 'ship' else payload->>'group' end;
  stat text:=payload->>'stat';
  observed_at timestamptz;
  gain numeric; xp_gain bigint; energy_cost integer; result jsonb;
begin
  if request_id is null or action is null or action not in ('crew','ship','purchase') or payload is null then
    raise exception 'INVALID_REQUEST' using errcode='22023'; end if;
  if group_name is null or group_name not in ('crew','ship') then raise exception 'INVALID_GROUP' using errcode='22023'; end if;
  if action in ('crew','ship') and (stat is null or stat not in ('attack','defense','speed','accuracy')) then
    raise exception 'INVALID_STAT' using errcode='22023'; end if;
  perform private.settle_combat_context(array[viewer_id]);
  select * into previous from private.training_requests r where r.character_id=viewer_id and r.request_id=training_action.request_id;
  if found then
    if previous.action<>action or previous.payload<>payload then raise exception 'REQUEST_CONFLICT' using errcode='22023'; end if;
    return previous.result;
  end if;
  observed_at:=clock_timestamp();
  perform private.settle_ship_upgrade(viewer_id,observed_at);
  perform private.assert_can_act(viewer_id);
  if exists(select 1 from private.combat_engagements where character_id=viewer_id and role='attacker') then
    raise exception 'IN_COMBAT'; end if;
  select * into captain from public.characters where id=viewer_id for update;
  if captain.location<>'the_harbor' then raise exception 'NOT_IN_HARBOR'; end if;
  select * into progress from private.character_training where character_id=viewer_id and training_group=group_name for update;
  select * into current_tier from private.training_tiers where training_group=group_name and id=progress.tier_id;
  if action='purchase' then
    select * into tier from private.training_tiers where training_group=group_name and id=payload->>'tier_id';
    if tier.id is null or tier.position<>current_tier.position+1 then raise exception 'INVALID_TIER' using errcode='22023'; end if;
    if progress.xp<tier.xp_required then raise exception 'NOT_ENOUGH_XP'; end if;
    if captain.gold_coins<tier.gold_cost then raise exception 'NOT_ENOUGH_GOLD'; end if;
    update public.characters set gold_coins=gold_coins-tier.gold_cost where id=viewer_id;
    update private.character_training set tier_id=tier.id where character_id=viewer_id and training_group=group_name;
    result:=jsonb_build_object('kind','purchase','group',group_name,'tier_id',tier.id,'tier_name',tier.name,'gold_cost',tier.gold_cost);
  else
    if payload->>'tier_id' is distinct from current_tier.id then raise exception 'STALE_TIER' using errcode='22023'; end if;
    energy_cost:=5;
    gain:=current_tier.stat_gain;
    if action='ship' then
      if exists(select 1 from private.ship_upgrade_jobs where character_id=viewer_id and applied_at is null) then raise exception 'SHIP_WORK_ACTIVE'; end if;
      if jsonb_typeof(payload->'energy_amount') is distinct from 'number'
        or (payload->>'energy_amount')::numeric<>trunc((payload->>'energy_amount')::numeric)
        or (payload->>'energy_amount')::numeric not between 5 and 100
      then raise exception 'INVALID_ENERGY' using errcode='22023'; end if;
      energy_cost:=(payload->>'energy_amount')::integer;
      gain:=trim_scale(round(gain/5,6)*energy_cost);
    else
      gain:=private.crew_training_gain(gain::bigint,private.combat_roll());
    end if;
    xp_gain:=energy_cost::bigint*1;
    if (to_jsonb(captain)->>(group_name||'_'||stat))::numeric>9007199254740991-gain
      or progress.xp>9007199254740991-xp_gain then raise exception 'PROGRESSION_LIMIT'; end if;
    select * into recovered from private.character_energy_snapshot(captain,observed_at);
    if recovered.energy<energy_cost then raise exception 'NOT_ENOUGH_ENERGY'; end if;
    update public.characters set energy=recovered.energy-energy_cost,energy_updated_at=recovered.energy_updated_at where id=viewer_id;
    if action='crew' then
      execute format('update public.characters set %I=%I+$1 where id=$2','crew_'||stat,'crew_'||stat) using gain,viewer_id;
      update private.character_training set xp=xp+xp_gain where character_id=viewer_id and training_group='crew';
      result:=jsonb_build_object('kind','crew','stat',stat,'stat_gain',gain,'xp_gain',xp_gain,'energy_cost',energy_cost,
        'perfect',gain>current_tier.stat_gain,'tier_id',current_tier.id);
    else
      insert into private.ship_upgrade_jobs(character_id,stat,workshop_id,workshop_name,energy_cost,stat_gain,xp_gain,config_revision,started_at,finishes_at)
        values(viewer_id,stat,current_tier.id,current_tier.name,energy_cost,gain,xp_gain,public.get_gameplay_revision(),
          observed_at,observed_at+make_interval(secs=>energy_cost::double precision*60)) returning * into job;
      result:=jsonb_build_object('kind','ship','job_id',job.id,'stat',stat,'stat_gain',gain,'xp_gain',xp_gain,
        'energy_cost',energy_cost,'finishes_at',job.finishes_at);
    end if;
  end if;
  insert into private.training_requests(character_id,request_id,action,payload,result) values(viewer_id,request_id,action,payload,result);
  perform private.notify_training(viewer_id);
  return result;
end;
$$;

revoke all on function private.notify_training(uuid),private.settle_ship_upgrade(uuid,timestamptz),
  private.training_state(uuid),private.crew_training_gain(bigint,double precision),private.training_action(text,jsonb,uuid)
  from public,anon,authenticated;
grant execute on function private.training_action(text,jsonb,uuid) to authenticated;

create or replace function public.train_crew(stat text,expected_tier_id text,request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.training_action('crew',jsonb_build_object('stat',stat,'tier_id',expected_tier_id),request_id);
$$;
create or replace function public.purchase_training_tier(training_group text,tier_id text,request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.training_action('purchase',jsonb_build_object('group',training_group,'tier_id',tier_id),request_id);
$$;
create or replace function public.start_ship_upgrade(stat text,energy_amount integer,expected_workshop_id text,request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.training_action('ship',jsonb_build_object('stat',stat,'energy_amount',energy_amount,'tier_id',expected_workshop_id),request_id);
$$;
revoke all on function public.train_crew(text,text,uuid),public.purchase_training_tier(text,text,uuid),
  public.start_ship_upgrade(text,integer,text,uuid) from public,anon,authenticated;
grant execute on function public.train_crew(text,text,uuid),public.purchase_training_tier(text,text,uuid),
  public.start_ship_upgrade(text,integer,text,uuid) to authenticated;

-- Canonical function bodies; scalar config tokens are substituted by config tooling.
-- Existing rows and reports are preserved; incompatible lower caps abort migration.
alter table public.characters
  alter column energy set default 100,
  alter column ship_health set default 100,
  alter column crew_health set default 100,
  alter column defence_order set default 'cannon',
  drop constraint characters_energy_check,
  add constraint characters_energy_check check(energy between 0 and 100),
  drop constraint characters_ship_health_check,
  add constraint characters_ship_health_check check(ship_health between 0 and 100),
  drop constraint characters_crew_health_check,
  add constraint characters_crew_health_check check(crew_health between 0 and 100);
alter table public.characters alter column ship_attack set default 10;
alter table public.characters alter column ship_defense set default 10;
alter table public.characters alter column ship_speed set default 10;
alter table public.characters alter column ship_accuracy set default 10;
alter table public.characters alter column crew_attack set default 10;
alter table public.characters alter column crew_defense set default 10;
alter table public.characters alter column crew_speed set default 10;
alter table public.characters alter column crew_accuracy set default 10;

-- Preserve historical counters when future limits decrease.
alter table private.combat_participants
  alter column defender_ammo set default 10,
  drop constraint combat_participants_round_check,
  add constraint combat_participants_round_check check(round>=0),
  drop constraint combat_participants_defender_ammo_check,
  add constraint combat_participants_defender_ammo_check check(defender_ammo>=0);

create or replace function private.energy_snapshot(stored_energy integer, anchor timestamptz, observed_at timestamptz)
returns table (energy integer, energy_updated_at timestamptz)
language sql immutable strict security invoker set search_path = ''
as $$
  with elapsed as (
    select greatest(0, floor(extract(epoch from (observed_at - anchor)) / 300)) as intervals
  ), recovery as (
    select intervals, least(100 - stored_energy,
      intervals * 5)::integer as gained from elapsed
  )
  select stored_energy + gained,
    case when stored_energy + gained = 100 then observed_at
      else anchor + intervals * make_interval(secs => 300) end
  from recovery;
$$;

create or replace function private.health_snapshot(value integer, anchor timestamptz, observed_at timestamptz, seconds integer)
returns integer language sql immutable strict security invoker set search_path = ''
as $$
  select least(100, value + least(100, greatest(0, floor(extract(epoch from (observed_at - anchor)) / seconds)))::integer);
$$;


-- Sea time is excluded before the ordinary interval calculation is used.
create or replace function private.character_energy_snapshot(c public.characters,observed_at timestamptz)
returns table(energy integer,energy_updated_at timestamptz)
language sql stable security invoker set search_path='' as $$
  select c.energy,c.energy_updated_at where c.energy_paused_at is not null
  union all
  select e.energy,e.energy_updated_at from private.energy_snapshot(c.energy,c.energy_updated_at,observed_at) e
    where c.energy_paused_at is null;
$$;
revoke all on function private.character_energy_snapshot(public.characters,timestamptz) from public,anon,authenticated;
update private.sea_location_types set active=false;
insert into private.sea_location_types(id,name,active) values
('deserted_island','Deserted island',true),
('village_island','Island village',true),
('deep_water','Deep water',true),
('sharp_rocks','Sharp rocks',true)
on conflict(id) do update set name=excluded.name,active=excluded.active;


create or replace function private.sea_state(c public.characters)
returns jsonb language sql stable security invoker set search_path='' as $$
  select jsonb_build_object(
    'state',case c.location when 'the_harbor' then 'in_harbor' when 'open_sea' then 'at_sea' else 'traveling' end,
    'version',c.sea_version,'step',c.sea_step,
    'visit_id',case when c.location='open_sea' then c.sea_visit_id end,
    'place',case when c.location='open_sea' then jsonb_build_object('id',c.sea_place_id,'name',c.sea_place_name) end,
    'options',case when c.location='open_sea' then coalesce((select jsonb_agg(
      jsonb_build_object('id',o.id,'place_id',o.place_id,'name',o.place_name) order by o.position)
      from private.sea_route_options o where o.character_id=c.id and o.visit_id=c.sea_visit_id),'[]'::jsonb) else '[]'::jsonb end,
    'journey',case when c.location='traveling' then jsonb_build_object(
      'id',c.travel_id,'kind',c.travel_kind,'from_step',c.sea_step,'target_step',c.travel_target_step,
      'destination',jsonb_build_object('id',c.travel_place_id,'name',c.travel_place_name),
      'started_at',c.travel_started_at,'arrives_at',c.travel_arrives_at) end);
$$;

-- Caller owns the character/combat locks. Arrival takes effect at its saved deadline.
create or replace function private.settle_sea_travel(captain_id uuid,observed_at timestamptz)
returns void language plpgsql volatile security invoker set search_path='' as $$
declare c public.characters%rowtype;
begin
  select * into c from public.characters where id=captain_id for update;
  if not found or c.location<>'traveling' or c.travel_arrives_at>observed_at then return; end if;
  if c.travel_kind='return' then
    update public.characters set location='the_harbor',sea_step=0,sea_visit_id=null,
      energy_updated_at=energy_updated_at+(travel_arrives_at-energy_paused_at),energy_paused_at=null,
      sea_version=gen_random_uuid(),travel_id=null,travel_kind=null,travel_target_step=null,
      travel_place_id=null,travel_place_name=null,travel_started_at=null,travel_arrives_at=null
      where id=captain_id;
    delete from private.sea_route_options where character_id=captain_id;
  else
    update public.characters set location='open_sea',sea_step=travel_target_step,
      max_sea_distance=greatest(max_sea_distance,travel_target_step),
      sea_place_id=travel_place_id,sea_place_name=travel_place_name,sea_version=gen_random_uuid(),
      travel_id=null,travel_kind=null,travel_target_step=null,travel_place_id=null,travel_place_name=null,
      travel_started_at=null,travel_arrives_at=null where id=captain_id;
  end if;
  perform private.notify_training(captain_id);
end;
$$;

create or replace function private.sea_travel_action(action text,expected_version uuid,option_id uuid,request_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare
  viewer_id uuid:=private.combat_captain();
  c public.characters%rowtype;
  previous private.sea_travel_requests%rowtype;
  chosen private.sea_route_options%rowtype;
  recovered record;
  observed_at timestamptz;
  deadline timestamptz;
  next_visit uuid;
  next_step integer;
  destination_id text;
  destination_name text;
  duration_seconds bigint;
  result jsonb;
  option_count integer;
begin
  if action is null or action not in ('depart','onward','return') or request_id is null or expected_version is null
    or (action='onward' and option_id is null) or (action<>'onward' and option_id is not null) then
    raise exception 'INVALID_REQUEST' using errcode='22023';
  end if;
  perform private.settle_combat_context(array[viewer_id]);
  select * into previous from private.sea_travel_requests r
    where r.character_id=viewer_id and r.request_id=sea_travel_action.request_id;
  if found then
    if previous.action<>action or previous.expected_version<>expected_version or previous.option_id is distinct from option_id then
      raise exception 'REQUEST_CONFLICT' using errcode='22023';
    end if;
    return previous.result;
  end if;
  observed_at:=clock_timestamp();
  perform private.settle_ship_upgrade(viewer_id,observed_at);
  select * into c from public.characters where id=viewer_id for update;
  select * into recovered from private.character_energy_snapshot(c,observed_at);
  if c.hospital_until is not null then raise exception 'IN_HOSPITAL'; end if;
  if exists(select 1 from private.combat_engagements where character_id=viewer_id) then raise exception 'IN_COMBAT'; end if;
  if c.sea_version<>expected_version then raise exception 'STALE_VOYAGE'; end if;
  if c.location='traveling' then raise exception 'TRAVEL_ACTIVE'; end if;
  if action='depart' then
    if c.location<>'the_harbor' then raise exception 'NOT_IN_HARBOR'; end if;
    if exists(select 1 from private.ship_upgrade_jobs where character_id=viewer_id and applied_at is null) then
      raise exception 'SHIP_WORK_ACTIVE';
    end if;
    if recovered.energy<5 then raise exception 'NOT_ENOUGH_ENERGY'; end if;
    next_step:=1; destination_id:='harbor_outskirts'; destination_name:='Outside the harbor';
  else
    if c.location<>'open_sea' then raise exception 'NOT_AT_SEA'; end if;
    if action='return' then
      next_step:=0; destination_id:='the_harbor'; destination_name:='The Harbor';
    else
      if c.sea_step=2147483647 then raise exception 'TRAVEL_LIMIT'; end if;
      select * into chosen from private.sea_route_options o
        where o.id=option_id and o.character_id=viewer_id and o.visit_id=c.sea_visit_id;
      if not found then raise exception 'STALE_ROUTE'; end if;
      next_step:=c.sea_step+1; destination_id:=chosen.place_id; destination_name:=chosen.place_name;
    end if;
  end if;
  duration_seconds:=case when action='return' then c.sea_step::bigint*60
    else 60 end;
  -- Keep deadlines representable by both PostgreSQL and the browser.
  if duration_seconds>=extract(epoch from ('9999-01-01Z'::timestamptz-observed_at))
    or next_step::bigint*60>=extract(epoch from ('9999-01-01Z'::timestamptz-observed_at)) then
    raise exception 'TRAVEL_LIMIT';
  end if;
  deadline:=observed_at+make_interval(secs=>duration_seconds::double precision);
  delete from private.sea_route_options where character_id=viewer_id;
  if action<>'return' then
    next_visit:=gen_random_uuid();
    insert into private.sea_route_options(character_id,visit_id,position,place_id,place_name)
      select viewer_id,next_visit,(row_number() over(order by draw,id)-1)::smallint,id,name
      from (select id,name,private.combat_roll() draw from private.sea_location_types where active order by draw,id limit 2) choices;
    get diagnostics option_count=row_count;
    if option_count<>2 then raise exception 'SEA_CATALOG_UNAVAILABLE'; end if;
  end if;
  update public.characters set location='traveling',sea_place_id=null,sea_place_name=null,sea_visit_id=next_visit,
    sea_version=gen_random_uuid(),travel_id=gen_random_uuid(),travel_kind=action,travel_target_step=next_step,
    travel_place_id=destination_id,travel_place_name=destination_name,travel_started_at=observed_at,travel_arrives_at=deadline,
    energy=case when action='depart' then recovered.energy-5 else energy end,
    energy_updated_at=case when action='depart' then recovered.energy_updated_at else energy_updated_at end,
    energy_paused_at=case when action='depart' then observed_at else energy_paused_at end
    where id=viewer_id returning * into c;
  result:=jsonb_build_object('journey_id',c.travel_id,'kind',action,'arrives_at',deadline);
  insert into private.sea_travel_requests(character_id,request_id,action,expected_version,option_id,result)
    values(viewer_id,request_id,action,expected_version,option_id,result);
  perform private.notify_training(viewer_id);
  return result;
end;
$$;

revoke all on function private.sea_state(public.characters),private.settle_sea_travel(uuid,timestamptz),
  private.sea_travel_action(text,uuid,uuid,uuid) from public,anon,authenticated;
grant execute on function private.sea_travel_action(text,uuid,uuid,uuid) to authenticated;

create or replace function public.depart_harbor(expected_version uuid,request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.sea_travel_action('depart',expected_version,null,request_id);
$$;
create or replace function public.choose_sea_route(expected_version uuid,option_id uuid,request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.sea_travel_action('onward',expected_version,option_id,request_id);
$$;
create or replace function public.return_to_harbor(expected_version uuid,request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.sea_travel_action('return',expected_version,null,request_id);
$$;
revoke all on function public.depart_harbor(uuid,uuid),public.choose_sea_route(uuid,uuid,uuid),
  public.return_to_harbor(uuid,uuid) from public,anon,authenticated;
grant execute on function public.depart_harbor(uuid,uuid),public.choose_sea_route(uuid,uuid,uuid),
  public.return_to_harbor(uuid,uuid) to authenticated;

-- Resource editing and hospital admission must preserve the travel invariants.
create or replace function private.guard_sea_resources()
returns trigger language plpgsql volatile security definer set search_path='' as $$
declare pause_end timestamptz;
begin
  new.max_sea_distance:=greatest(new.max_sea_distance,new.sea_step);
  if tg_op='UPDATE' then
    -- Preserve a due offline record before hospital admission or another server edit.
    new.max_sea_distance:=greatest(new.max_sea_distance,old.max_sea_distance,
      case when old.travel_kind in ('depart','onward')
        and old.travel_arrives_at<=coalesce(new.hospital_started_at,clock_timestamp())
        then old.travel_target_step else 0 end);
  end if;
  if tg_op='UPDATE' and old.energy_paused_at is not null and new.location<>'the_harbor'
    and new.energy_paused_at is not distinct from old.energy_paused_at
    and new.energy_updated_at is distinct from old.energy_updated_at then
    new.energy_paused_at:=case when new.travel_kind='return' then least(new.energy_updated_at,new.travel_arrives_at) else new.energy_updated_at end;
  end if;
  if new.hospital_until is not null and new.location<>'the_harbor' then
    pause_end:=coalesce(new.hospital_started_at,clock_timestamp());
    if new.travel_kind='return' then pause_end:=least(pause_end,new.travel_arrives_at); end if;
    new.energy_updated_at:=new.energy_updated_at+greatest(interval '0',pause_end-new.energy_paused_at);
    new.energy_paused_at:=null; new.location:='the_harbor'; new.sea_step:=0; new.sea_visit_id:=null;
    new.sea_place_id:=null; new.sea_place_name:=null; new.sea_version:=gen_random_uuid();
    new.travel_id:=null; new.travel_kind:=null; new.travel_target_step:=null;
    new.travel_place_id:=null; new.travel_place_name:=null; new.travel_started_at:=null; new.travel_arrives_at:=null;
    delete from private.sea_route_options where character_id=new.id;
  end if;
  return new;
end;
$$;
revoke all on function private.guard_sea_resources() from public,anon,authenticated;
drop trigger if exists characters_guard_sea_resources on public.characters;
create trigger characters_guard_sea_resources before insert or update on public.characters
for each row execute function private.guard_sea_resources();

create or replace function private.sync_harbor_player()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.location='the_harbor' or new.travel_kind='return' then
    insert into public.harbor_players(character_id,display_name,arrives_at)
      values(new.id,new.display_name,case when new.travel_kind='return' then new.travel_arrives_at end)
      on conflict(character_id) do update set display_name=excluded.display_name,arrives_at=excluded.arrives_at
      where (harbor_players.display_name,harbor_players.arrives_at)
        is distinct from (excluded.display_name,excluded.arrives_at);
  else
    delete from public.harbor_players where character_id=new.id;
  end if;
  return new;
end;
$$;
drop trigger characters_sync_harbor_player on public.characters;
create trigger characters_sync_harbor_player after insert or update on public.characters
for each row execute function private.sync_harbor_player();

create or replace function private.sync_character_profile()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into public.character_profiles(character_id,display_name,location,created_at,arrives_at,arrival_location,
    max_sea_distance,arrival_max_sea_distance)
    values(new.id,new.display_name,new.location,new.created_at,new.travel_arrives_at,
      case when new.location='traveling' then case when new.travel_kind='return' then 'the_harbor' else 'open_sea' end end,
      new.max_sea_distance,case when new.travel_kind in ('depart','onward')
        and new.travel_target_step>new.max_sea_distance then new.travel_target_step end)
    on conflict(character_id) do update set display_name=excluded.display_name,location=excluded.location,
      created_at=excluded.created_at,arrives_at=excluded.arrives_at,arrival_location=excluded.arrival_location,
      max_sea_distance=excluded.max_sea_distance,arrival_max_sea_distance=excluded.arrival_max_sea_distance
    where (character_profiles.display_name,character_profiles.location,character_profiles.created_at,
      character_profiles.arrives_at,character_profiles.arrival_location,
      character_profiles.max_sea_distance,character_profiles.arrival_max_sea_distance) is distinct from
      (excluded.display_name,excluded.location,excluded.created_at,excluded.arrives_at,excluded.arrival_location,
      excluded.max_sea_distance,excluded.arrival_max_sea_distance);
  return new;
end;
$$;
drop trigger characters_sync_profile on public.characters;
create trigger characters_sync_profile after insert or update on public.characters
for each row execute function private.sync_character_profile();
revoke all on function private.sync_harbor_player(),private.sync_character_profile() from public,anon,authenticated;
create or replace function private.combat_snapshot(c public.characters, observed_at timestamptz)
returns jsonb language sql stable security invoker set search_path = ''
as $$
  select jsonb_build_object(
    'id', c.id, 'name', c.display_name, 'ammo', 10, 'defence_order', c.defence_order,
    'ship_health', private.health_snapshot(c.ship_health, c.ship_recovery_at, observed_at, 30),
    'crew_health', private.health_snapshot(c.crew_health, c.crew_recovery_at, observed_at, 10),
    'ship', jsonb_build_object('attack',c.ship_attack,'defense',c.ship_defense,'speed',c.ship_speed,'accuracy',c.ship_accuracy),
    'crew', jsonb_build_object('attack',c.crew_attack,'defense',c.crew_defense,'speed',c.crew_speed,'accuracy',c.crew_accuracy)
  );
$$;

create or replace function private.visible_combatant(snapshot jsonb, own boolean, revealed boolean)
returns jsonb language sql immutable security invoker set search_path = ''
as $$
  select jsonb_build_object(
    'id',snapshot->'id','name',snapshot->'name',
    'ship_health',snapshot->'ship_health','crew_health',snapshot->'crew_health',
    'ammo',case when own then snapshot->'ammo' end,
    'ship',case when own then snapshot->'ship' end,
    'crew',case when own then snapshot->'crew' end,
    'cannons',case when own or revealed then 'Basic cannons' end,
    'weapon',case when own or revealed then 'Cutlasses' end);
$$;

create or replace function private.combat_hit_chance(accuracy numeric, speed numeric)
returns double precision language plpgsql immutable strict security invoker set search_path='' as $$
declare ratio double precision;
  extreme constant double precision := 64;
  exponent constant double precision := 0.5;
  factor double precision := power(extreme,exponent);
begin
  if accuracy<=0 or speed<=0 then raise exception 'INVALID_COMBAT_STAT' using errcode='22023'; end if;
  ratio:=(accuracy/speed)::double precision;
  if ratio<=1/extreme then return 0; end if;
  if ratio>=extreme then return 1; end if;
  if ratio<=1 then return (factor*power(ratio,exponent)-1)/(2*(factor-1)); end if;
  return 1-(factor*power(1/ratio,exponent)-1)/(2*(factor-1));
end;
$$;

create or replace function private.combat_damage_reduction(attack numeric, defense numeric)
returns numeric language plpgsql immutable strict security invoker set search_path='' as $$
declare ratio numeric;
  zero_ratio constant numeric := 32;
  full_ratio constant numeric := 25;
  equal_reduction constant numeric := 0.5;
begin
  if attack<=0 or defense<=0 then raise exception 'INVALID_COMBAT_STAT' using errcode='22023'; end if;
  ratio:=defense/attack;
  if ratio<=1/zero_ratio then return 0; end if;
  if ratio>=full_ratio then return 1; end if;
  if ratio<=1 then return equal_reduction*(1+ln(ratio)/ln(zero_ratio)); end if;
  return equal_reduction+(1-equal_reduction)*ln(ratio)/ln(full_ratio);
end;
$$;

create or replace function private.combat_damage(attack numeric, defense numeric)
returns integer language plpgsql immutable strict security invoker set search_path='' as $$
declare reduction numeric; strength_log numeric;
begin
  reduction:=private.combat_damage_reduction(attack,defense);
  if reduction>=1 then return 0; end if;
  strength_log:=log(greatest(1::numeric,attack/1));
  return greatest(1,round(
    (7*strength_log*strength_log+
     27*strength_log+30)*(1-reduction)))::integer;
end;
$$;

create or replace function private.resolve_combat_round(input_state jsonb, player_order text, rolls double precision[])
returns jsonb language plpgsql immutable security invoker set search_path = ''
as $$
declare
  a jsonb := input_state->'attacker';
  d jsonb := input_state->'defender';
  phase text := input_state->>'phase';
  group_name text := case when phase = 'sea' then 'ship' else 'crew' end;
  health_key text := group_name || '_health';
  defender_order text;
  next_phase text := phase;
  round_no integer := (input_state->>'round')::integer + 1;
  a_damage integer := 0; d_damage integer := 0;
  a_hit boolean := false; d_hit boolean := false;
  chance double precision;
  a_down boolean; d_down boolean;
  outcome text; winner text; transition text;
  boarded boolean;
  result_state jsonb;
begin
  if input_state->>'status' <> 'active' or round_no > 25 then raise exception 'COMBAT_FINISHED'; end if;
  if player_order is null or
    (phase = 'sea' and player_order not in ('fire', 'board', 'retreat')) or
    (phase = 'boarding' and player_order not in ('crew_attack', 'disengage', 'retreat')) then
    raise exception 'INVALID_ORDER' using errcode = '22023';
  end if;
  if cardinality(rolls) <> 3 or exists(select 1 from unnest(rolls) r where r is null or r < 0 or r >= 1) then
    raise exception 'INVALID_ROLLS';
  end if;
  defender_order := case when phase = 'boarding' then 'crew_attack'
    when d->>'defence_order' = 'cannon' and (d->>'ammo')::integer >= 1 then 'fire' else 'board' end;
  if player_order = 'fire' and (a->>'ammo')::integer < 1 then raise exception 'NO_AMMO'; end if;
  if player_order in ('fire', 'crew_attack') then
    chance := private.combat_hit_chance((a->group_name->>'accuracy')::numeric,(d->group_name->>'speed')::numeric);
    a_hit := rolls[1] < chance;
    if a_hit then a_damage := least((d->>health_key)::integer,
      private.combat_damage((a->group_name->>'attack')::numeric,(d->group_name->>'defense')::numeric)); end if;
  end if;
  if defender_order in ('fire', 'crew_attack') then
    chance := private.combat_hit_chance((d->group_name->>'accuracy')::numeric,(a->group_name->>'speed')::numeric);
    d_hit := rolls[2] < chance;
    if d_hit then d_damage := least((a->>health_key)::integer,
      private.combat_damage((d->group_name->>'attack')::numeric,(a->group_name->>'defense')::numeric)); end if;
  end if;
  a := a || jsonb_build_object(health_key, (a->>health_key)::integer - d_damage,
    'ammo', (a->>'ammo')::integer - case when player_order = 'fire' then 1 else 0 end);
  d := d || jsonb_build_object(health_key, (d->>health_key)::integer - a_damage,
    'ammo', (d->>'ammo')::integer - case when defender_order = 'fire' then 1 else 0 end);
  if (a->>'ship_health')::integer=0 then a:=a || jsonb_build_object('crew_health',0); end if;
  if (d->>'ship_health')::integer=0 then d:=d || jsonb_build_object('crew_health',0); end if;
  a_down := (a->>'ship_health')::integer = 0 or (a->>'crew_health')::integer = 0;
  d_down := (d->>'ship_health')::integer = 0 or (d->>'crew_health')::integer = 0;
  if a_down and d_down then outcome := 'draw';
  elsif a_down or d_down then
    outcome := case when phase = 'sea' then 'hull_victory' else 'boarding_victory' end;
    winner := case when a_down then d->>'id' else a->>'id' end;
  elsif player_order = 'retreat' then outcome := 'retreated';
  elsif round_no >= 25 then outcome := 'draw';
  elsif phase = 'boarding' and player_order = 'disengage' then
    next_phase := 'sea'; transition := 'disengaged';
  elsif phase = 'sea' and (player_order = 'board' or defender_order = 'board') then
    if player_order = 'board' and defender_order = 'board' then boarded := true;
    else
      chance := greatest(0.2, least(0.9, 0.7 + 0.3 *
        ((a->'ship'->>'speed')::double precision - (d->'ship'->>'speed')::double precision) /
        ((a->'ship'->>'speed')::double precision + (d->'ship'->>'speed')::double precision) *
        case when player_order = 'board' then 1 else -1 end));
      boarded := rolls[3] < chance;
    end if;
    transition := case when boarded then 'boarded' else 'boarding_failed' end;
    if boarded then next_phase := 'boarding'; end if;
  end if;
  result_state := input_state || jsonb_build_object('attacker',a,'defender',d,'round',round_no,'phase',next_phase,
    'status',case when outcome is null then 'active' else 'completed' end,
    'outcome',outcome,'winner_id',winner);
  return jsonb_build_object('state',result_state,'event',jsonb_build_object(
    'round',round_no,'phase',phase,'attacker_order',player_order,'defender_order',defender_order,
    'attacker_hit',a_hit,'defender_hit',d_hit,'attacker_damage',a_damage,'defender_damage',d_damage,
    'transition',transition,'outcome',outcome));
end;
$$;

create or replace function private.advance_shared_combat(battle_id uuid, actor uuid, player_order text, request_id uuid, occurred_at timestamptz, timed_out boolean)
returns void language plpgsql volatile security invoker set search_path='' as $$
declare b private.combats%rowtype; p private.combat_participants%rowtype;
  resolved jsonb; s jsonb; d jsonb; a jsonb; personal_status text; ending text; winner uuid;
begin
  select * into b from private.combats where id=battle_id for update;
  select * into p from private.combat_participants where combat_id=battle_id and character_id=actor;
  if b.status<>'active' or p.status<>'active' then return; end if;
  resolved:=private.resolve_combat_round(jsonb_build_object('status','active','phase',p.phase,'round',p.round,
    'attacker',p.snapshot,'defender',b.state->'defender' || jsonb_build_object('ammo',p.defender_ammo)),
    player_order,array[private.combat_roll(),private.combat_roll(),private.combat_roll()]);
  s:=resolved->'state'; a:=s->'attacker'; d:=s->'defender';
  personal_status:=case
    when (a->>'ship_health')::integer=0 or (a->>'crew_health')::integer=0 then 'defeated'
    when player_order='retreat' then 'retreated'
    when (s->>'round')::integer>=25 then 'draw' else 'active' end;
  -- Final blow remains credited even if the simultaneous counterattack also downs its author.
  if (d->>'ship_health')::integer=0 or (d->>'crew_health')::integer=0 then
    ending:=case when (d->>'ship_health')::integer=0 then 'hull_victory' else 'boarding_victory' end;
    winner:=actor; personal_status:='victory';
  end if;
  update private.combat_participants set snapshot=a,phase=s->>'phase',round=(s->>'round')::integer,
    status=personal_status,defender_ammo=(d->>'ammo')::integer,
    deadline=least(b.hard_deadline,occurred_at+make_interval(secs => 120)),
    finished_at=case when personal_status<>'active' then occurred_at end,
    hits=hits+case when (resolved->'event'->>'attacker_hit')::boolean then 1 else 0 end,
    damage=damage+(resolved->'event'->>'attacker_damage')::integer
    where combat_id=battle_id and character_id=actor;
  update public.characters set ship_health=(a->>'ship_health')::integer,crew_health=(a->>'crew_health')::integer,
    ship_recovery_at=occurred_at,crew_recovery_at=occurred_at,
    hospital_started_at=case when (a->>'crew_health')::integer=0 then occurred_at else hospital_started_at end,
    hospital_until=case when (a->>'crew_health')::integer=0 then occurred_at+make_interval(secs=>300) else hospital_until end,
    protected_until=case when personal_status<>'active' then occurred_at+make_interval(secs => 300) end where id=actor;
  update public.characters set ship_health=(d->>'ship_health')::integer,crew_health=(d->>'crew_health')::integer,
    ship_recovery_at=occurred_at,crew_recovery_at=occurred_at,
    hospital_started_at=case when (d->>'crew_health')::integer=0 then occurred_at else hospital_started_at end,
    hospital_until=case when (d->>'crew_health')::integer=0 then occurred_at+make_interval(secs=>300) else hospital_until end
    where id=b.defender_id;
  if personal_status<>'active' then delete from private.combat_engagements where character_id=actor and combat_id=battle_id; end if;
  if ending is not null then
    update public.characters set ship_recovery_at=occurred_at,crew_recovery_at=occurred_at,protected_until=occurred_at+make_interval(secs => 300)
      where id in(select character_id from private.combat_participants where combat_id=battle_id and status='active');
    update private.combat_participants set status='assist',finished_at=occurred_at where combat_id=battle_id and status='active';
  elsif not exists(select 1 from private.combat_participants where combat_id=battle_id and status='active') then
    ending:=case when personal_status='defeated' then 'defended' when personal_status='draw' then 'draw' else 'retreated' end;
    winner:=case when personal_status='defeated' then b.defender_id end;
  end if;
  perform private.append_combat_event(battle_id,actor,request_id,
    resolved->'event' || jsonb_build_object('kind','round','actor_name',p.snapshot->>'name',
      'at',occurred_at,'timed_out',timed_out,'participant_result',personal_status,'outcome',ending));
  update private.combats set state=state || jsonb_build_object('defender',d,'status',case when ending is null then 'active' else 'completed' end,
    'outcome',ending,'winner_id',winner),
    deadline=coalesce((select min(deadline) from private.combat_participants where combat_id=battle_id and status='active'),occurred_at),
    finished_at=case when ending is not null then occurred_at end where id=battle_id;
  if ending is not null then
    delete from private.combat_engagements where combat_id=battle_id;
    update public.characters set protected_until=occurred_at+make_interval(secs => 300) where id=b.defender_id;
  end if;
  perform private.notify_combat(battle_id);
end;
$$;

create or replace function private.get_combat_preview(target_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare viewer_id uuid:=private.combat_captain(); a public.characters%rowtype; d public.characters%rowtype;
  own_engagement private.combat_engagements%rowtype; target_engagement private.combat_engagements%rowtype;
  a_snapshot jsonb; d_snapshot jsonb; energy_now integer; reason text; observed_at timestamptz;
begin
  if target_id is null then return jsonb_build_object('error','CHARACTER_NOT_FOUND'); end if;
  perform private.settle_combat_context(array[viewer_id,target_id]);
  observed_at:=clock_timestamp();
  perform private.settle_ship_upgrade(viewer_id,observed_at);
  perform private.settle_ship_upgrade(target_id,observed_at);
  select * into a from public.characters where id=viewer_id;
  select * into d from public.characters where id=target_id;
  if d.id is null then return jsonb_build_object('error','CHARACTER_NOT_FOUND'); end if;
  select * into own_engagement from private.combat_engagements where character_id=viewer_id;
  select * into target_engagement from private.combat_engagements where character_id=target_id;
  a_snapshot:=private.combat_snapshot(a,observed_at);
  d_snapshot:=private.combat_snapshot(d,observed_at);
  if own_engagement.character_id is not null then a_snapshot:=a_snapshot || jsonb_build_object('ship_health',a.ship_health,'crew_health',a.crew_health); end if;
  if target_engagement.character_id is not null then d_snapshot:=d_snapshot || jsonb_build_object('ship_health',d.ship_health,'crew_health',d.crew_health); end if;
  select energy into energy_now from private.character_energy_snapshot(a,observed_at);
  reason:=case when a.hospital_until is not null then 'IN_HOSPITAL'
    when d.hospital_until is not null then 'TARGET_IN_HOSPITAL'
    when a.location<>'the_harbor' then 'AT_SEA'
    when d.location<>'the_harbor' then 'TARGET_AT_SEA'
    when viewer_id=target_id then 'SELF_ATTACK'
    when own_engagement.role='attacker' then 'IN_COMBAT'
    when own_engagement.role='defender' then 'DEFENDING'
    when target_engagement.role='attacker' then 'TARGET_IN_COMBAT'
    when exists(select 1 from private.combat_participants where combat_id=target_engagement.combat_id and character_id=viewer_id) then 'ALREADY_PARTICIPATED'
    when target_engagement.character_id is null and d.protected_until>observed_at then 'TARGET_PROTECTED'
    when (a_snapshot->>'ship_health')::integer<1 or (a_snapshot->>'crew_health')::integer<1 then 'NO_HEALTH'
    when (d_snapshot->>'ship_health')::integer<1 or (d_snapshot->>'crew_health')::integer<1 then 'TARGET_NO_HEALTH'
    when energy_now<10 then 'NOT_ENOUGH_ENERGY' end;
  return jsonb_build_object('attacker',private.visible_combatant(a_snapshot,true,false),
    'defender',private.visible_combatant(d_snapshot,false,false),'energy',energy_now,'can_start',reason is null,'reason',reason,
    'active_combat_id',case when own_engagement.role='attacker' then own_engagement.combat_id end,
    'join_combat_id',case when target_engagement.role='defender' then target_engagement.combat_id end,
    'target_protected_until',case when target_engagement.character_id is null and d.protected_until>observed_at then d.protected_until end,
    'observed_at',observed_at);
end;
$$;

create or replace function private.start_combat(target_id uuid,request_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare viewer_id uuid:=private.combat_captain(); previous private.combat_participants%rowtype;
  preview jsonb; a public.characters%rowtype; d public.characters%rowtype; recovered record;
  battle_id uuid; initial_state jsonb; observed_at timestamptz; b private.combats%rowtype; snapshot jsonb; joining boolean;
begin
  if request_id is null then raise exception 'INVALID_REQUEST' using errcode='22023'; end if;
  perform private.settle_combat_context(array[viewer_id,target_id]);
  select * into previous from private.combat_participants where character_id=viewer_id and start_request_id=request_id;
  if found then
    if (select defender_id from private.combats where id=previous.combat_id)<>target_id then return jsonb_build_object('error','REQUEST_CONFLICT'); end if;
    return jsonb_build_object('battle',private.combat_view(previous.combat_id,viewer_id));
  end if;
  preview:=private.get_combat_preview(target_id);
  if preview ? 'error' then return preview; end if;
  if not (preview->>'can_start')::boolean then return jsonb_build_object('error',preview->>'reason'); end if;
  observed_at:=clock_timestamp();
  perform private.settle_ship_upgrade(viewer_id,observed_at);
  perform private.settle_ship_upgrade(target_id,observed_at);
  select * into a from public.characters where id=viewer_id;
  select * into d from public.characters where id=target_id;
  select * into recovered from private.character_energy_snapshot(a,observed_at);
  snapshot:=private.combat_snapshot(a,observed_at);
  battle_id:=(preview->>'join_combat_id')::uuid; joining:=battle_id is not null;
  if not joining then
    initial_state:=jsonb_build_object('attacker',snapshot,'defender',private.combat_snapshot(d,observed_at),
      'status','active','outcome',null,'winner_id',null);
    insert into private.combats(attacker_id,defender_id,start_request_id,rules_version,state,started_at,deadline,hard_deadline)
      values(viewer_id,target_id,request_id,2,initial_state,observed_at,observed_at+make_interval(secs => 120),observed_at+make_interval(secs => 600))
      returning id into battle_id;
    insert into private.combat_engagements(character_id,combat_id,role) values(target_id,battle_id,'defender');
    update public.characters set protected_until=null,ship_health=(initial_state->'defender'->>'ship_health')::integer,
      crew_health=(initial_state->'defender'->>'crew_health')::integer,ship_recovery_at=observed_at,crew_recovery_at=observed_at where id=target_id;
  end if;
  select * into b from private.combats where id=battle_id for update;
  insert into private.combat_participants(combat_id,character_id,start_request_id,snapshot,joined_at,deadline)
    values(battle_id,viewer_id,request_id,snapshot,observed_at,least(b.hard_deadline,observed_at+make_interval(secs => 120)));
  insert into private.combat_engagements(character_id,combat_id,role) values(viewer_id,battle_id,'attacker');
  update public.characters set energy=recovered.energy-10,energy_updated_at=recovered.energy_updated_at,protected_until=null,
    ship_health=(snapshot->>'ship_health')::integer,crew_health=(snapshot->>'crew_health')::integer,
    ship_recovery_at=observed_at,crew_recovery_at=observed_at where id=viewer_id;
  perform private.append_combat_event(battle_id,viewer_id,request_id,jsonb_build_object(
    'kind',case when joining then 'joined' else 'started' end,'actor_name',a.display_name,'at',observed_at));
  perform private.notify_combat(battle_id);
  return jsonb_build_object('battle',private.combat_view(battle_id,viewer_id));
end;
$$;

create or replace function private.submit_combat_order(battle_id uuid,expected_round integer,player_order text,request_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare viewer_id uuid:=private.combat_captain(); b private.combats%rowtype; p private.combat_participants%rowtype; previous jsonb;
begin
  if request_id is null or expected_round is null or expected_round<0 or expected_round>=25 then raise exception 'INVALID_REQUEST' using errcode='22023'; end if;
  select * into b from private.combats where id=battle_id;
  if not found or not exists(select 1 from private.combat_participants where combat_id=battle_id and character_id=viewer_id) then
    return jsonb_build_object('error','COMBAT_NOT_FOUND'); end if;
  perform private.settle_combat_context(array[viewer_id,b.defender_id]);
  select * into b from private.combats where id=battle_id;
  select * into p from private.combat_participants where combat_id=battle_id and character_id=viewer_id;
  select event into previous from private.combat_rounds where combat_id=battle_id and actor_id=viewer_id and combat_rounds.request_id=submit_combat_order.request_id;
  if found then
    if previous->>'kind'<>'round' or (previous->>'round')::integer<>expected_round+1 or previous->>'attacker_order'<>player_order then
      return jsonb_build_object('error','REQUEST_CONFLICT'); end if;
    return jsonb_build_object('battle',private.combat_view(battle_id,viewer_id));
  end if;
  if b.status='completed' or p.status<>'active' then return jsonb_build_object('battle',private.combat_view(battle_id,viewer_id)); end if;
  perform private.assert_can_act(viewer_id);
  if p.round<>expected_round then return jsonb_build_object('error','STALE_ROUND'); end if;
  if player_order is null or (p.phase='sea' and player_order not in ('fire','board','retreat'))
    or (p.phase='boarding' and player_order not in ('crew_attack','disengage','retreat')) then return jsonb_build_object('error','INVALID_ORDER'); end if;
  if player_order='fire' and (p.snapshot->>'ammo')::integer<1 then return jsonb_build_object('error','NO_AMMO'); end if;
  perform private.advance_shared_combat(battle_id,viewer_id,player_order,request_id,clock_timestamp(),false);
  return jsonb_build_object('battle',private.combat_view(battle_id,viewer_id));
end;
$$;

create or replace function private.get_game_state()
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare c public.characters%rowtype; active private.combats%rowtype; engagement private.combat_engagements%rowtype; observed_at timestamptz;
  recovered record; ship_hp integer; crew_hp integer; health_next_at timestamptz; last_id uuid;
begin
  if auth.uid() is null or not private.is_registered_player() then return null; end if;
  select * into c from public.characters where user_id=auth.uid();
  if not found then return null; end if;
  perform private.settle_combat_context(array[c.id]);
  observed_at:=clock_timestamp();
  perform private.settle_ship_upgrade(c.id,observed_at);
  select * into c from public.characters where id=c.id;
  select * into engagement from private.combat_engagements where character_id=c.id;
  select * into active from private.combats where id=engagement.combat_id;
  select * into recovered from private.character_energy_snapshot(c,observed_at);
  ship_hp:=case when active.id is not null or c.hospital_until is not null then c.ship_health else private.health_snapshot(c.ship_health,c.ship_recovery_at,observed_at,30) end;
  crew_hp:=case when active.id is not null or c.hospital_until is not null then c.crew_health else private.health_snapshot(c.crew_health,c.crew_recovery_at,observed_at,10) end;
  if active.id is null and c.hospital_until is null then
    health_next_at:=least(case when ship_hp<100 then c.ship_recovery_at+(ship_hp-c.ship_health+1)*make_interval(secs => 30) end,
      case when crew_hp<100 then c.crew_recovery_at+(crew_hp-c.crew_health+1)*make_interval(secs => 10) end);
  end if;
  select b.id into last_id from private.combats b where b.defender_id=c.id
    or exists(select 1 from private.combat_participants where combat_id=b.id and character_id=c.id)
    order by b.started_at desc,b.id desc limit 1;
  return jsonb_build_object('energy',recovered.energy,'energy_next_at',case when c.energy_paused_at is null and recovered.energy<100 then recovered.energy_updated_at+make_interval(secs => 300) end,
    'sea',private.sea_state(c),'gold_coins',c.gold_coins,'bank_gold_coins',c.bank_gold_coins,'training',private.training_state(c.id),
    'hospital_until',c.hospital_until,'observed_at',observed_at,'ship_health',ship_hp,'crew_health',crew_hp,'health_next_at',health_next_at,
    'active_combat_id',active.id,'combat_next_at',active.deadline,'last_combat_id',last_id,
    'active_attack',case when engagement.role='attacker' then jsonb_build_object('battle_id',active.id,'target_id',active.defender_id) end,
    'defence_order',c.defence_order,'protected_until',case when c.protected_until>observed_at then c.protected_until end,
    'ship_attack',c.ship_attack,'ship_defense',c.ship_defense,'ship_speed',c.ship_speed,'ship_accuracy',c.ship_accuracy,
    'crew_attack',c.crew_attack,'crew_defense',c.crew_defense,'crew_speed',c.crew_speed,'crew_accuracy',c.crew_accuracy);
end;
$$;


create or replace function public.list_harbor_players(requested_page integer default 0)
returns jsonb
language sql stable security invoker set search_path = ''
as $$
  with totals as (
    select count(*)::integer as total from public.harbor_players where arrives_at is null or arrives_at<=statement_timestamp()
  ), paging as (
    select total, least(greatest(coalesce(requested_page, 0), 0),
      greatest(0, (total - 1) / 20)) as page from totals
  )
  select jsonb_build_object(
    'total', total, 'page', page, 'observed_at',statement_timestamp(),
    'next_arrival_at',(select min(arrives_at) from public.character_profiles where arrival_location='the_harbor' and arrives_at>statement_timestamp()),
    'players', coalesce((
      select jsonb_agg(to_jsonb(player) order by player.display_name, player.character_id)
      from (
        select character_id, display_name from public.harbor_players where arrives_at is null or arrives_at<=statement_timestamp()
        order by display_name, character_id limit 20 offset paging.page * 20
      ) player
    ), '[]'::jsonb)
  ) from paging;
$$;

-- Gold Coins are separate carried and bank balances.
alter table public.characters
  alter column gold_coins set default 0,
  drop constraint characters_gold_coins_check,
  add constraint characters_gold_coins_check check (gold_coins between 0 and 9007199254740991),
  drop constraint characters_bank_gold_coins_check,
  add constraint characters_bank_gold_coins_check check (bank_gold_coins between 0 and 9007199254740991);

create or replace function private.transfer_gold(direction text, amount numeric, request_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare
  viewer_id uuid := private.combat_captain();
  captain public.characters%rowtype;
  previous private.bank_transfers%rowtype;
  coins bigint;
begin
  if request_id is null then raise exception 'INVALID_REQUEST' using errcode='22023'; end if;
  if direction is null or direction not in ('deposit','withdraw') then
    raise exception 'INVALID_DIRECTION' using errcode='22023'; end if;
  if amount is null or amount < 1 or amount > 9007199254740991 or amount <> trunc(amount) then
    raise exception 'INVALID_AMOUNT' using errcode='22023'; end if;
  coins := amount::bigint;
  perform private.settle_combat_context(array[viewer_id]);
  select * into previous from private.bank_transfers t
    where t.character_id=viewer_id and t.request_id=transfer_gold.request_id;
  if found then
    if previous.direction <> direction or previous.amount <> coins then
      raise exception 'REQUEST_CONFLICT' using errcode='22023';
    end if;
    return jsonb_build_object('direction',previous.direction,'amount',previous.amount,
      'gold_coins',previous.gold_coins,'bank_gold_coins',previous.bank_gold_coins);
  end if;
  perform private.assert_can_act(viewer_id);
  if exists(select 1 from private.combat_engagements where character_id=viewer_id and role='attacker') then
    raise exception 'IN_COMBAT' using errcode='P0001'; end if;
  select * into captain from public.characters where id=viewer_id for update;
  if captain.location <> 'the_harbor' then raise exception 'NOT_IN_HARBOR' using errcode='P0001'; end if;
  if direction='deposit' then
    if captain.gold_coins < coins then raise exception 'NOT_ENOUGH_GOLD' using errcode='P0001'; end if;
    if captain.bank_gold_coins > 9007199254740991 - coins then
      raise exception 'BALANCE_LIMIT' using errcode='P0001'; end if;
    update public.characters set gold_coins=gold_coins-coins, bank_gold_coins=bank_gold_coins+coins
      where id=viewer_id returning * into captain;
  else
    if captain.bank_gold_coins < coins then raise exception 'NOT_ENOUGH_BANK_GOLD' using errcode='P0001'; end if;
    if captain.gold_coins > 9007199254740991 - coins then
      raise exception 'BALANCE_LIMIT' using errcode='P0001'; end if;
    update public.characters set gold_coins=gold_coins+coins, bank_gold_coins=bank_gold_coins-coins
      where id=viewer_id returning * into captain;
  end if;
  insert into private.bank_transfers(character_id,request_id,direction,amount,gold_coins,bank_gold_coins)
    values(viewer_id,request_id,direction,coins,captain.gold_coins,captain.bank_gold_coins);
  insert into public.player_game_events(character_id,revision) values(viewer_id,1)
    on conflict(character_id) do update set revision=player_game_events.revision+1;
  return jsonb_build_object('direction',direction,'amount',coins,
    'gold_coins',captain.gold_coins,'bank_gold_coins',captain.bank_gold_coins);
end;
$$;
revoke all on function private.transfer_gold(text,numeric,uuid) from public,anon,authenticated;
grant execute on function private.transfer_gold(text,numeric,uuid) to authenticated;

create or replace function public.transfer_gold(direction text, amount numeric, request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.transfer_gold(direction,amount,request_id);
$$;
revoke all on function public.transfer_gold(text,numeric,uuid) from public,anon,authenticated;
grant execute on function public.transfer_gold(text,numeric,uuid) to authenticated;

-- A sinking ship kills its crew. Every new death starts one hospital stay.
create or replace function private.admit_to_hospital()
returns trigger language plpgsql volatile security definer set search_path='' as $$
declare admitted_at timestamptz:=clock_timestamp();
begin
  if new.ship_health=0 then new.crew_health:=0; end if;
  if new.crew_health=0 and new.hospital_until is null then
    new.hospital_started_at:=admitted_at;
    new.hospital_until:=admitted_at+make_interval(secs=>300);
  end if;
  return new;
end;
$$;
revoke all on function private.admit_to_hospital() from public,anon,authenticated;
drop trigger if exists characters_admit_to_hospital on public.characters;
create trigger characters_admit_to_hospital before insert or update of ship_health,crew_health on public.characters
for each row execute function private.admit_to_hospital();

create or replace function private.sync_hospital_patient()
returns trigger language plpgsql volatile security definer set search_path='' as $$
begin
  if new.hospital_until is not null then
    insert into public.hospital_patients(character_id,display_name,hospital_until)
    values(new.id,new.display_name,new.hospital_until)
    on conflict(character_id) do update set display_name=excluded.display_name,hospital_until=excluded.hospital_until
      where hospital_patients.display_name is distinct from excluded.display_name
        or hospital_patients.hospital_until is distinct from excluded.hospital_until;
  else
    delete from public.hospital_patients where character_id=new.id;
  end if;
  if tg_op='INSERT' or old.hospital_until is distinct from new.hospital_until then
    perform private.notify_training(new.id);
  end if;
  return new;
end;
$$;
revoke all on function private.sync_hospital_patient() from public,anon,authenticated;
drop trigger if exists characters_sync_hospital_patient on public.characters;
create trigger characters_sync_hospital_patient after insert or update on public.characters
for each row execute function private.sync_hospital_patient();

-- Caller owns the character/combat locks. Expiry is based only on database time.
create or replace function private.settle_hospital(captain_id uuid,observed_at timestamptz)
returns void language plpgsql volatile security invoker set search_path='' as $$
begin
  update public.characters set ship_health=100,crew_health=100,
    ship_recovery_at=hospital_until,crew_recovery_at=hospital_until,hospital_started_at=null,hospital_until=null
    where id=captain_id and hospital_until<=observed_at;
end;
$$;
create or replace function private.assert_can_act(captain_id uuid)
returns void language plpgsql volatile security invoker set search_path='' as $$
begin
  perform private.settle_hospital(captain_id,clock_timestamp());
  if exists(select 1 from public.characters where id=captain_id and hospital_until is not null) then
    raise exception 'IN_HOSPITAL' using errcode='P0001';
  end if;
  if exists(select 1 from public.characters where id=captain_id and location<>'the_harbor') then
    raise exception 'NOT_IN_HARBOR' using errcode='P0001';
  end if;
end;
$$;

-- Environmental death during a fight ends that encounter without a fabricated final blow.
create or replace function private.interrupt_hospital_combats(captain_ids uuid[])
returns void language plpgsql volatile security invoker set search_path='' as $$
declare b private.combats%rowtype; patient public.characters%rowtype; observed_at timestamptz:=clock_timestamp();
begin
  for b in select * from private.combats where status='active'
    and id in(select combat_id from private.combat_engagements where character_id=any(captain_ids))
    and exists(select 1 from private.combat_engagements e join public.characters c on c.id=e.character_id
      where e.combat_id=combats.id and c.hospital_until is not null)
    order by id for update
  loop
    select c.* into patient from public.characters c join private.combat_engagements e on e.character_id=c.id
      where e.combat_id=b.id and c.hospital_until is not null order by c.hospital_started_at,c.id limit 1;
    update private.combat_participants p set
      status=case when c.hospital_until is not null then 'defeated' else 'draw' end,
      snapshot=p.snapshot || jsonb_build_object('ship_health',c.ship_health,'crew_health',c.crew_health),
      finished_at=observed_at
      from public.characters c where p.combat_id=b.id and p.character_id=c.id and p.status='active';
    update private.combats set state=state || jsonb_build_object('status','completed','outcome','draw','winner_id',null,
      'defender',state->'defender' || (select jsonb_build_object('ship_health',ship_health,'crew_health',crew_health)
        from public.characters where id=b.defender_id)),finished_at=observed_at,deadline=observed_at where id=b.id;
    update public.characters set ship_recovery_at=observed_at,crew_recovery_at=observed_at,
      protected_until=observed_at+make_interval(secs=>300)
      where id in(select character_id from private.combat_engagements where combat_id=b.id);
    perform private.append_combat_event(b.id,patient.id,gen_random_uuid(),
      jsonb_build_object('kind','hospital','actor_name',patient.display_name,'at',observed_at,'outcome','draw'));
    delete from private.combat_engagements where combat_id=b.id;
    perform private.notify_combat(b.id);
  end loop;
end;
$$;

create or replace function private.settle_combat_context(captain_ids uuid[])
returns void language plpgsql volatile security invoker set search_path='' as $$
declare p record; captain_id uuid;
begin
  perform private.lock_combat_context(captain_ids);
  perform private.interrupt_hospital_combats(captain_ids);
  for p in select cp.combat_id,cp.character_id,cp.deadline from private.combat_participants cp
    where cp.status='active' and cp.deadline<=clock_timestamp()
      and cp.combat_id in(select combat_id from private.combat_engagements where character_id=any(captain_ids))
    order by cp.deadline,cp.character_id
  loop
    perform private.advance_shared_combat(p.combat_id,p.character_id,'retreat',gen_random_uuid(),p.deadline,true);
  end loop;
  for captain_id in select distinct id from unnest(captain_ids) id where id is not null order by id loop
    perform private.settle_hospital(captain_id,clock_timestamp());
    perform private.settle_sea_travel(captain_id,clock_timestamp());
  end loop;
end;
$$;
revoke all on function private.settle_hospital(uuid,timestamptz),private.assert_can_act(uuid),
  private.interrupt_hospital_combats(uuid[]) from public,anon,authenticated;

create or replace function private.save_defence_orders(preset text)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare viewer_id uuid:=private.combat_captain();
begin
  if preset is null or preset not in ('cannon','boarding') then raise exception 'INVALID_PRESET' using errcode='22023'; end if;
  perform private.settle_combat_context(array[viewer_id]);
  perform private.assert_can_act(viewer_id);
  update public.characters set defence_order=preset where id=viewer_id;
  return jsonb_build_object('preset',preset);
end;
$$;

create or replace function public.get_navigation_lock()
returns jsonb language sql volatile security invoker set search_path='' as $$
  select jsonb_build_object('attack',s->'active_attack','hospital_until',s->'hospital_until','sea_state',s#>>'{sea,state}')
  from (select public.get_game_state() s) state;
$$;
revoke all on function public.get_navigation_lock() from public,anon,authenticated;
grant execute on function public.get_navigation_lock() to authenticated;

create or replace function public.list_hospital_patients(requested_page integer default 0)
returns jsonb language sql stable security invoker set search_path='' as $$
  with patients as (
    select * from public.hospital_patients where hospital_until>now()
  ), totals as (
    select count(*)::integer total,min(hospital_until) next_discharge_at from patients
  ), paging as (
    select total,next_discharge_at,least(greatest(coalesce(requested_page,0),0),
      greatest(0,(total-1)/20)) page from totals
  )
  select jsonb_build_object('total',total,'page',page,'observed_at',now(),'next_discharge_at',next_discharge_at,
    'patients',coalesce((select jsonb_agg(to_jsonb(p) order by p.display_name,p.character_id)
      from (select * from patients order by display_name,character_id
        limit 20 offset paging.page*20) p),'[]'::jsonb))
    from paging;
$$;
revoke all on function public.list_hospital_patients(integer) from public,anon,authenticated;
grant execute on function public.list_hospital_patients(integer) to authenticated;

-- Derive damage by phase from saved events, including existing encounters.
create or replace function private.combat_people(battle_id uuid)
returns jsonb language sql stable security invoker set search_path='' as $$
  with damage as materialized (
    select r.actor_id,
      coalesce(sum((r.event->>'attacker_damage')::integer) filter (where r.event->>'phase'='sea'),0) ship_damage,
      coalesce(sum((r.event->>'attacker_damage')::integer) filter (where r.event->>'phase'='boarding'),0) crew_damage,
      coalesce(sum((r.event->>'defender_damage')::integer) filter (where r.event->>'phase'='sea'),0) defender_ship_damage,
      coalesce(sum((r.event->>'defender_damage')::integer) filter (where r.event->>'phase'='boarding'),0) defender_crew_damage,
      count(*) filter (where (r.event->>'defender_hit')::boolean) defender_hits
    from private.combat_rounds r where r.combat_id=battle_id group by r.actor_id
  )
  select coalesce(jsonb_agg(person order by joined_at,id),'[]'::jsonb) from (
    select p.joined_at,p.character_id id,jsonb_build_object('id',p.character_id,'name',p.snapshot->>'name',
      'role','attacker','status',p.status,'hits',p.hits,'damage',p.damage,
      'ship_damage',coalesce(d.ship_damage,0),'crew_damage',coalesce(d.crew_damage,0),
      'ship_health',p.snapshot->'ship_health','crew_health',p.snapshot->'crew_health','phase',p.phase) person
    from private.combat_participants p left join damage d on d.actor_id=p.character_id where p.combat_id=battle_id
    union all select b.started_at,b.defender_id,jsonb_build_object('id',b.defender_id,'name',b.state->'defender'->>'name',
      'role','defender','status',case when b.status='active' then 'active'
        when (b.state#>>'{defender,crew_health}')::integer=0 or (b.state#>>'{defender,ship_health}')::integer=0 then 'defeated' else 'survived' end,
      'hits',coalesce(d.hits,0),'damage',coalesce(d.ship_damage,0)+coalesce(d.crew_damage,0),
      'ship_damage',coalesce(d.ship_damage,0),'crew_damage',coalesce(d.crew_damage,0),
      'ship_health',b.state->'defender'->'ship_health','crew_health',b.state->'defender'->'crew_health','phase',null)
    from private.combats b cross join (
      select sum(defender_hits) hits,sum(defender_ship_damage) ship_damage,sum(defender_crew_damage) crew_damage from damage
    ) d where b.id=battle_id
  ) people;
$$;

-- Profiles share the existing public patient projection without exposing character data.
create or replace function public.get_hospital_status(target_id uuid)
returns jsonb language sql stable security invoker set search_path='' as $$
  select jsonb_build_object('hospital_until',(select hospital_until from public.hospital_patients
    where character_id=target_id and hospital_until>now()),'observed_at',now());
$$;
revoke all on function public.get_hospital_status(uuid) from public,anon,authenticated;
grant execute on function public.get_hospital_status(uuid) to authenticated;


-- Public location and deadlines resolve without requiring the owner to log in.
create or replace function public.get_character_status(target_id uuid)
returns jsonb language sql stable security invoker set search_path='' as $$
  select jsonb_build_object(
    'location',case when p.arrives_at<=statement_timestamp() then p.arrival_location else p.location end,
    'arrives_at',case when p.arrives_at>statement_timestamp() then p.arrives_at end,
    'max_sea_distance',greatest(p.max_sea_distance,
      case when p.arrives_at<=statement_timestamp() then p.arrival_max_sea_distance end),
    'hospital_until',(select hospital_until from public.hospital_patients
      where character_id=target_id and hospital_until>statement_timestamp()),
    'observed_at',statement_timestamp())
  from public.character_profiles p where p.character_id=target_id;
$$;
revoke all on function public.get_character_status(uuid) from public,anon,authenticated;
grant execute on function public.get_character_status(uuid) to authenticated;
-- Circulation updates share the inventory transaction and never expose ownership.
create or replace function private.record_item_circulation_delta(target_item text,delta numeric)
returns void language plpgsql volatile security definer set search_path='' as $$
declare current_total numeric; recorded timestamptz;
begin
  if delta=0 then return; end if;
  update private.item_circulation
    set total=total+delta,updated_at=greatest(clock_timestamp(),updated_at+interval '1 microsecond')
    where item_id=target_item returning total,updated_at into current_total,recorded;
  if not found then raise exception 'CIRCULATION_NOT_INITIALIZED'; end if;
  insert into private.item_circulation_history(item_id,transaction_id,recorded_at,total)
    values(target_item,pg_current_xact_id(),recorded,current_total)
    on conflict(item_id,transaction_id) do update set recorded_at=excluded.recorded_at,total=excluded.total;
end;
$$;
revoke all on function private.record_item_circulation_delta(text,numeric) from public,anon,authenticated;

create or replace function private.initialize_item_circulation()
returns trigger language plpgsql security definer set search_path='' as $$
declare started timestamptz:=clock_timestamp();
begin
  insert into private.item_circulation(item_id,total,initial_total,tracked_since,updated_at)
    values(new.id,0,0,started,started);
  insert into private.item_circulation_history(item_id,transaction_id,recorded_at,total)
    values(new.id,pg_current_xact_id(),started,0);
  return new;
end;
$$;
revoke all on function private.initialize_item_circulation() from public,anon,authenticated;
drop trigger if exists initialize_item_circulation on private.item_definitions;
create trigger initialize_item_circulation after insert on private.item_definitions
  for each row execute function private.initialize_item_circulation();

create or replace function private.track_item_circulation()
returns trigger language plpgsql security definer set search_path='' as $$
declare change record;
begin
  if tg_op='INSERT' then
    for change in select n.item_id,sum(coalesce((to_jsonb(n)->>'quantity')::numeric,1)) delta
      from new_items n group by n.item_id order by n.item_id
    loop perform private.record_item_circulation_delta(change.item_id,change.delta); end loop;
  elsif tg_op='DELETE' then
    for change in select o.item_id,-sum(coalesce((to_jsonb(o)->>'quantity')::numeric,1)) delta
      from old_items o group by o.item_id order by o.item_id
    loop perform private.record_item_circulation_delta(change.item_id,change.delta); end loop;
  else
    for change in select item_id,sum(amount) delta from (
      select n.item_id,coalesce((to_jsonb(n)->>'quantity')::numeric,1) amount from new_items n
      union all select o.item_id,-coalesce((to_jsonb(o)->>'quantity')::numeric,1) from old_items o
    ) changes group by item_id having sum(amount)<>0 order by item_id
    loop perform private.record_item_circulation_delta(change.item_id,change.delta); end loop;
  end if;
  return null;
end;
$$;
revoke all on function private.track_item_circulation() from public,anon,authenticated;

drop trigger if exists circulation_insert on private.item_stacks;
drop trigger if exists circulation_update on private.item_stacks;
drop trigger if exists circulation_delete on private.item_stacks;
create trigger circulation_insert after insert on private.item_stacks
  referencing new table as new_items for each statement execute function private.track_item_circulation();
create trigger circulation_update after update on private.item_stacks
  referencing old table as old_items new table as new_items for each statement execute function private.track_item_circulation();
create trigger circulation_delete after delete on private.item_stacks
  referencing old table as old_items for each statement execute function private.track_item_circulation();
drop trigger if exists circulation_insert on private.item_instances;
drop trigger if exists circulation_update on private.item_instances;
drop trigger if exists circulation_delete on private.item_instances;
create trigger circulation_insert after insert on private.item_instances
  referencing new table as new_items for each statement execute function private.track_item_circulation();
create trigger circulation_update after update on private.item_instances
  referencing old table as old_items new table as new_items for each statement execute function private.track_item_circulation();
create trigger circulation_delete after delete on private.item_instances
  referencing old table as old_items for each statement execute function private.track_item_circulation();

-- Definitions are durable. Removing a definition or changing its ownership shape is rejected.
do $inventory$ begin if exists(select 1 from private.item_categories old left join (values
('crew_weapons','Crew Weapons',0),
('cannons','Cannons',1),
('medical','Medical',2),
('boosters','Boosters',3),
('materials','Materials',4),
('miscellaneous','Miscellaneous',5)
) incoming(id,name,position) using(id) where incoming.id is null) then raise exception 'Existing category IDs must be preserved'; end if; if exists(select 1 from private.item_definitions old left join (values
('cutlass','crew_weapons','Sailor''s Cutlass','A broad, curved blade with a brass guard and a salt-worn leather grip. A dependable companion in the close quarters of a boarding action.','Crew weapon. Its individual Damage and Accuracy are shown below.','/images/items/cutlass.png','equipment',false,'crew_weapon',true),
('deck_cannon','cannons','Deck Cannon','A compact iron cannon mounted on a sturdy oak carriage. Built to bring a broadside to bear without crowding the deck.','Ship armament. Its individual Damage and Accuracy are shown below.','/images/items/cannon.png','equipment',false,'cannons',true),
('linen_bandages','medical','Linen Bandages','Clean linen, rolled and tucked away from the spray. An essential part of a ship surgeon''s supplies.','Medical supply intended for treating wounded crew. Medical use will be available later.','/images/items/bandages.png','consumable',true,null::text,true),
('drill_tonic','boosters','Drill Tonic','An herbal preparation in a stout green bottle. Quartermasters keep it aside for the most demanding practice sessions.','Intended to temporarily improve the chance of a Perfect Drill. Training effects will be available later.','/images/items/tonic.png','consumable',true,null::text,true),
('oak_planks','materials','Oak Planks','Seasoned oak boards bound with hemp rope. Their close grain and solid weight make them prized by shipwrights.','Shipbuilding material. No active effect.','/images/items/timber.png','passive',true,null::text,true),
('brass_compass','miscellaneous','Brass Compass','A brass compass worn smooth by years in a captain''s coat. The needle still finds north, whatever the sea has in store.','A keepsake from life at sea. No active effect.','/images/items/compass.png','passive',true,null::text,true)
) incoming(id,category_id,name,description,effect_description,image_path,kind,stackable,slot,active) using(id) where incoming.id is null or old.kind<>incoming.kind or old.stackable<>incoming.stackable or old.slot is distinct from incoming.slot) then raise exception 'Existing item IDs, kinds and slots must be preserved'; end if; end $inventory$;
insert into private.item_categories(id,name,position) values
('crew_weapons','Crew Weapons',0),
('cannons','Cannons',1),
('medical','Medical',2),
('boosters','Boosters',3),
('materials','Materials',4),
('miscellaneous','Miscellaneous',5)
on conflict(id) do update set name=excluded.name,position=excluded.position;
insert into private.item_definitions(id,category_id,name,description,effect_description,image_path,kind,stackable,slot,active) values
('cutlass','crew_weapons','Sailor''s Cutlass','A broad, curved blade with a brass guard and a salt-worn leather grip. A dependable companion in the close quarters of a boarding action.','Crew weapon. Its individual Damage and Accuracy are shown below.','/images/items/cutlass.png','equipment',false,'crew_weapon',true),
('deck_cannon','cannons','Deck Cannon','A compact iron cannon mounted on a sturdy oak carriage. Built to bring a broadside to bear without crowding the deck.','Ship armament. Its individual Damage and Accuracy are shown below.','/images/items/cannon.png','equipment',false,'cannons',true),
('linen_bandages','medical','Linen Bandages','Clean linen, rolled and tucked away from the spray. An essential part of a ship surgeon''s supplies.','Medical supply intended for treating wounded crew. Medical use will be available later.','/images/items/bandages.png','consumable',true,null::text,true),
('drill_tonic','boosters','Drill Tonic','An herbal preparation in a stout green bottle. Quartermasters keep it aside for the most demanding practice sessions.','Intended to temporarily improve the chance of a Perfect Drill. Training effects will be available later.','/images/items/tonic.png','consumable',true,null::text,true),
('oak_planks','materials','Oak Planks','Seasoned oak boards bound with hemp rope. Their close grain and solid weight make them prized by shipwrights.','Shipbuilding material. No active effect.','/images/items/timber.png','passive',true,null::text,true),
('brass_compass','miscellaneous','Brass Compass','A brass compass worn smooth by years in a captain''s coat. The needle still finds north, whatever the sea has in store.','A keepsake from life at sea. No active effect.','/images/items/compass.png','passive',true,null::text,true)
on conflict(id) do update set category_id=excluded.category_id,name=excluded.name,description=excluded.description,effect_description=excluded.effect_description,image_path=excluded.image_path,active=excluded.active;


create or replace function private.list_inventory(category_id text default null,search_term text default '',requested_page integer default 0)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare
  viewer_id uuid:=private.combat_captain();
  page_size integer:=25;
  result jsonb;
begin
  if requested_page is null or requested_page<0 or search_term is null or length(search_term)>100 then
    raise exception 'INVALID_FILTER' using errcode='22023'; end if;
  if category_id is not null and not exists(select 1 from private.item_categories c where c.id=category_id) then
    raise exception 'INVALID_CATEGORY' using errcode='22023'; end if;
  with owned as (
    select s.id,'stack'::text entry_type,s.item_id,s.quantity,null::jsonb stats
      from private.item_stacks s where s.character_id=viewer_id
    union all
    select i.id,'instance',i.item_id,1::bigint,jsonb_build_object('damage',i.damage,'accuracy',i.accuracy)
      from private.item_instances i where i.character_id=viewer_id
  ), matching as (
    select o.*,d.name,d.category_id,d.kind,d.description,d.effect_description,d.image_path
      from owned o join private.item_definitions d on d.id=o.item_id
      where (list_inventory.category_id is null or d.category_id=list_inventory.category_id)
        and strpos(lower(d.name),lower(btrim(search_term)))>0
  ), bounds as (
    select count(*) total,least(requested_page,greatest(0,(count(*)-1)/page_size))::integer page from matching
  ), items as (
    select m.*,c.total::text circulation from matching m
      join private.item_circulation c on c.item_id=m.item_id
      order by lower(m.name) collate "C",m.item_id,m.id,m.entry_type
      limit page_size offset (select page::bigint*page_size from bounds)
  )
  select jsonb_build_object('items',coalesce((select jsonb_agg(to_jsonb(i)
      order by lower(i.name) collate "C",i.item_id,i.id,i.entry_type) from items i),'[]'::jsonb),
    'total',b.total,'page',b.page,'page_size',page_size) into result from bounds b;
  return result;
end;
$$;
revoke all on function private.list_inventory(text,text,integer) from public,anon,authenticated;
grant execute on function private.list_inventory(text,text,integer) to authenticated;
create or replace function public.list_inventory(category_id text default null,search_term text default '',requested_page integer default 0)
returns jsonb language sql stable security invoker set search_path='' as $$
  select private.list_inventory(category_id,search_term,requested_page);
$$;
revoke all on function public.list_inventory(text,text,integer) from public,anon,authenticated;
grant execute on function public.list_inventory(text,text,integer) to authenticated;

create or replace function private.trash_inventory_item(entry_id uuid,entry_type text,quantity numeric,request_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare
  viewer_id uuid:=private.combat_captain();
  previous private.inventory_requests%rowtype;
  stack private.item_stacks%rowtype;
  item private.item_instances%rowtype;
  payload jsonb;
  result jsonb;
  amount bigint;
  remaining bigint;
  item_name text;
begin
  if request_id is null or entry_id is null then raise exception 'INVALID_REQUEST' using errcode='22023'; end if;
  if entry_type is null or entry_type not in ('stack','instance') then
    raise exception 'INVALID_ITEM_TYPE' using errcode='22023'; end if;
  if quantity is null or quantity<1 or quantity>9007199254740991 or quantity<>trunc(quantity)
    or (entry_type='instance' and quantity<>1) then
    raise exception 'INVALID_QUANTITY' using errcode='22023'; end if;
  amount:=quantity::bigint;
  payload:=jsonb_build_object('entry_id',entry_id,'entry_type',entry_type,'quantity',amount);
  perform private.settle_combat_context(array[viewer_id]);
  select * into previous from private.inventory_requests r
    where r.character_id=viewer_id and r.request_id=trash_inventory_item.request_id;
  if found then
    if previous.payload<>payload then raise exception 'REQUEST_CONFLICT' using errcode='22023'; end if;
    return previous.result;
  end if;
  perform private.assert_can_act(viewer_id);
  if exists(select 1 from private.combat_engagements where character_id=viewer_id and role='attacker') then
    raise exception 'IN_COMBAT' using errcode='P0001'; end if;
  if entry_type='stack' then
    select * into stack from private.item_stacks s where s.id=entry_id and s.character_id=viewer_id for update;
    if not found then raise exception 'ITEM_NOT_FOUND' using errcode='P0001'; end if;
    if stack.quantity<amount then raise exception 'NOT_ENOUGH_ITEMS' using errcode='P0001'; end if;
    select name into item_name from private.item_definitions where id=stack.item_id;
    remaining:=stack.quantity-amount;
    if remaining=0 then delete from private.item_stacks where id=stack.id;
    else update private.item_stacks set quantity=remaining where id=stack.id; end if;
  else
    select * into item from private.item_instances i where i.id=entry_id and i.character_id=viewer_id for update;
    if not found then raise exception 'ITEM_NOT_FOUND' using errcode='P0001'; end if;
    select name into item_name from private.item_definitions where id=item.item_id;
    remaining:=0;
    delete from private.item_instances where id=item.id;
  end if;
  result:=jsonb_build_object('entry_id',entry_id,'entry_type',entry_type,'quantity',amount,
    'name',item_name,'remaining',remaining);
  insert into private.inventory_requests(character_id,request_id,payload,result)
    values(viewer_id,request_id,payload,result);
  perform private.notify_training(viewer_id);
  return result;
end;
$$;
revoke all on function private.trash_inventory_item(uuid,text,numeric,uuid) from public,anon,authenticated;
grant execute on function private.trash_inventory_item(uuid,text,numeric,uuid) to authenticated;
create or replace function public.trash_inventory_item(entry_id uuid,entry_type text,quantity numeric,request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.trash_inventory_item(entry_id,entry_type,quantity,request_id);
$$;
revoke all on function public.trash_inventory_item(uuid,text,numeric,uuid) from public,anon,authenticated;
grant execute on function public.trash_inventory_item(uuid,text,numeric,uuid) to authenticated;

-- Large ranges use bounded indexed lookups; stored history keeps every transaction.
create or replace function private.get_item_circulation(target_item text,period text default 'all')
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare
  viewer_id uuid:=private.combat_captain();
  counter private.item_circulation%rowtype;
  observed timestamptz:=statement_timestamp();
  range_start timestamptz;
  initial numeric;
  point_limit integer:=500;
  points jsonb;
  sampled boolean;
begin
  if period is null or period not in ('1m','3m','6m','1y','3y','all') then
    raise exception 'INVALID_PERIOD' using errcode='22023'; end if;
  select * into counter from private.item_circulation where item_id=target_item;
  if not found then raise exception 'ITEM_NOT_FOUND' using errcode='22023'; end if;
  observed:=greatest(observed,counter.updated_at);
  range_start:=greatest(counter.tracked_since,case period
    when '1m' then observed-interval '1 month'
    when '3m' then observed-interval '3 months'
    when '6m' then observed-interval '6 months'
    when '1y' then observed-interval '1 year'
    when '3y' then observed-interval '3 years'
    else counter.tracked_since end);
  select coalesce((select h.total from private.item_circulation_history h
    where h.item_id=target_item and h.recorded_at<=range_start
    order by h.recorded_at desc,h.id desc limit 1),counter.initial_total) into initial;
  select count(*)>point_limit into sampled from (
    select 1 from private.item_circulation_history h
    where h.item_id=target_item and h.recorded_at>range_start and h.recorded_at<observed
    limit point_limit+1
  ) limited;
  if not sampled then
    select coalesce(jsonb_agg(jsonb_build_object('at',h.recorded_at,'total',h.total::text)
      order by h.recorded_at,h.id),'[]'::jsonb) into points
      from private.item_circulation_history h where h.item_id=target_item
        and h.recorded_at>range_start and h.recorded_at<observed;
  else
    select jsonb_agg(jsonb_build_object('at',t.sample_at,'total',coalesce(h.total,initial)::text)
      order by t.sample_at) into points
    from (select range_start+(observed-range_start)*(n::double precision/(point_limit+1)) as sample_at
      from generate_series(1,point_limit) n) t
    left join lateral (
      select total from private.item_circulation_history h
      where h.item_id=target_item and h.recorded_at<=t.sample_at
      order by h.recorded_at desc,h.id desc limit 1
    ) h on true;
  end if;
  return jsonb_build_object('item_id',target_item,'period',period,'total',counter.total::text,
    'tracked_since',counter.tracked_since,'from',range_start,'to',observed,'sampled',sampled,
    'points',jsonb_build_array(jsonb_build_object('at',range_start,'total',initial::text)) ||
      points || jsonb_build_array(jsonb_build_object('at',observed,'total',counter.total::text)));
end;
$$;
revoke all on function private.get_item_circulation(text,text) from public,anon,authenticated;
grant execute on function private.get_item_circulation(text,text) to authenticated;
create or replace function public.get_item_circulation(target_item text,period text default 'all')
returns jsonb language sql stable security invoker set search_path='' as $$
  select private.get_item_circulation(target_item,period);
$$;
revoke all on function public.get_item_circulation(text,text) from public,anon,authenticated;
grant execute on function public.get_item_circulation(text,text) to authenticated;

create or replace function public.get_gameplay_revision()
returns text language sql immutable security invoker set search_path='' as $$
  select '4697f396f8a440c4ef012c3662341b9579e03d04dcf404bfabbe11450d76782a'::text;
$$;
revoke all on function public.get_gameplay_revision() from public;
grant execute on function public.get_gameplay_revision() to anon,authenticated;
