-- Generated by npm run config:sync. Edit config/gameplay.json or supabase/templates/gameplay.sql.
-- gameplay-revision: 26c391f022e6f6cb8c4758b2a49697efc0e8302455d8f8e59c72a8434d92a624


-- Tier IDs and positions are durable; balance values may change.
do $catalog$ begin if exists(select 1 from private.training_tiers old left join (values
('crew','crew_1',0,'Deck Drills',0,0,1),
('crew','crew_2',1,'Harbor Exercises',100,250,2),
('crew','crew_3',2,'Sailor Training',500,1000,4),
('crew','crew_4',3,'Veteran Drills',1500,4000,8),
('crew','crew_5',4,'Boarding Practice',4000,15000,20),
('crew','crew_6',5,'Officer Training',10000,50000,50),
('crew','crew_7',6,'Elite Exercises',20000,150000,125),
('crew','crew_8',7,'Master Drills',40000,500000,300),
('crew','crew_9',8,'Legendary Training',65000,1500000,750),
('crew','crew_10',9,'Admiral Exercises',100000,5000000,1500),
('ship','ship_1',0,'Deck Workbench',0,0,1),
('ship','ship_2',1,'Harbor Workshop',100,250,2),
('ship','ship_3',2,'Shipwright Workshop',500,1000,4),
('ship','ship_4',3,'Reinforced Workshop',1500,4000,8),
('ship','ship_5',4,'Advanced Workshop',4000,15000,20),
('ship','ship_6',5,'Master Shipwright',10000,50000,50),
('ship','ship_7',6,'Naval Workshop',20000,150000,125),
('ship','ship_8',7,'Grand Workshop',40000,500000,300),
('ship','ship_9',8,'Royal Dockworks',65000,1500000,750),
('ship','ship_10',9,'Admiral Dockworks',100000,5000000,1500)
) incoming(training_group,id,position,name,xp_required,gold_cost,stat_gain) using(training_group,id) where incoming.id is null or incoming.position<>old.position) then raise exception 'Existing tier IDs and positions must be preserved'; end if; end $catalog$;
insert into private.training_tiers(training_group,id,position,name,xp_required,gold_cost,stat_gain) values
('crew','crew_1',0,'Deck Drills',0,0,1),
('crew','crew_2',1,'Harbor Exercises',100,250,2),
('crew','crew_3',2,'Sailor Training',500,1000,4),
('crew','crew_4',3,'Veteran Drills',1500,4000,8),
('crew','crew_5',4,'Boarding Practice',4000,15000,20),
('crew','crew_6',5,'Officer Training',10000,50000,50),
('crew','crew_7',6,'Elite Exercises',20000,150000,125),
('crew','crew_8',7,'Master Drills',40000,500000,300),
('crew','crew_9',8,'Legendary Training',65000,1500000,750),
('crew','crew_10',9,'Admiral Exercises',100000,5000000,1500),
('ship','ship_1',0,'Deck Workbench',0,0,1),
('ship','ship_2',1,'Harbor Workshop',100,250,2),
('ship','ship_3',2,'Shipwright Workshop',500,1000,4),
('ship','ship_4',3,'Reinforced Workshop',1500,4000,8),
('ship','ship_5',4,'Advanced Workshop',4000,15000,20),
('ship','ship_6',5,'Master Shipwright',10000,50000,50),
('ship','ship_7',6,'Naval Workshop',20000,150000,125),
('ship','ship_8',7,'Grand Workshop',40000,500000,300),
('ship','ship_9',8,'Royal Dockworks',65000,1500000,750),
('ship','ship_10',9,'Admiral Dockworks',100000,5000000,1500)
on conflict(training_group,id) do update set name=excluded.name,xp_required=excluded.xp_required,gold_cost=excluded.gold_cost,stat_gain=excluded.stat_gain;
insert into private.ship_work_sizes(id,name,units,duration_seconds) values
('small','Small',1,300),
('medium','Medium',5,1500),
('large','Large',10,3000)
on conflict(id) do update set name=excluded.name,units=excluded.units,duration_seconds=excluded.duration_seconds;
delete from private.ship_work_sizes where id not in ('small','medium','large');


create or replace function private.initialize_training_progress()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into private.character_training(character_id,training_group,tier_id)
    select new.id,training_group,id from private.training_tiers where position=0;
  return new;
end;
$$;
revoke all on function private.initialize_training_progress() from public,anon,authenticated;
drop trigger if exists initialize_training_progress on public.characters;
create trigger initialize_training_progress after insert on public.characters
for each row execute function private.initialize_training_progress();
insert into private.character_training(character_id,training_group,tier_id)
  select c.id,t.training_group,t.id from public.characters c cross join private.training_tiers t where t.position=0
  on conflict(character_id,training_group) do nothing;

create or replace function private.notify_training(captain_id uuid)
returns void language sql volatile security invoker set search_path='' as $$
  insert into public.player_game_events(character_id,revision) values(captain_id,1)
    on conflict(character_id) do update set revision=player_game_events.revision+1;
$$;

-- Caller holds the character/combat locks. The caller's observation time also drives snapshots.
create or replace function private.settle_ship_upgrade(captain_id uuid, observed_at timestamptz)
returns void language plpgsql volatile security invoker set search_path='' as $$
declare job private.ship_upgrade_jobs%rowtype;
begin
  select * into job from private.ship_upgrade_jobs where character_id=captain_id and applied_at is null for update;
  if not found or job.finishes_at>observed_at then return; end if;
  execute format('update public.characters set %I=%I+$1 where id=$2','ship_'||job.stat,'ship_'||job.stat)
    using job.stat_gain,captain_id;
  update private.character_training set xp=xp+job.xp_gain where character_id=captain_id and training_group='ship';
  update private.ship_upgrade_jobs set applied_at=observed_at where id=job.id;
  perform private.notify_training(captain_id);
end;
$$;

create or replace function private.training_state(captain_id uuid)
returns jsonb language sql stable security invoker set search_path='' as $$
  select jsonb_build_object(
    'progress',(select jsonb_object_agg(training_group,jsonb_build_object('xp',xp,'tier_id',tier_id))
      from private.character_training where character_id=captain_id),
    'ship_job',(select to_jsonb(j)-'character_id'-'config_revision' from private.ship_upgrade_jobs j
      where character_id=captain_id and applied_at is null),
    'last_ship_job',(select to_jsonb(j)-'character_id'-'config_revision' from private.ship_upgrade_jobs j
      where character_id=captain_id and applied_at is not null order by finishes_at desc,id desc limit 1));
$$;

-- Deterministic resolver is internal only; callers cannot choose the random roll.
create or replace function private.crew_training_gain(base_gain bigint, roll double precision)
returns bigint language plpgsql immutable strict security invoker set search_path='' as $$
begin
  if base_gain<1 or roll<0 or roll>=1 then raise exception 'INVALID_TRAINING_ROLL' using errcode='22023'; end if;
  return base_gain * case when roll < 100 / 10000.0
    then 2 else 1 end;
end;
$$;

create or replace function private.training_action(action text,payload jsonb,request_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare
  viewer_id uuid:=private.combat_captain();
  captain public.characters%rowtype;
  progress private.character_training%rowtype;
  tier private.training_tiers%rowtype;
  current_tier private.training_tiers%rowtype;
  size private.ship_work_sizes%rowtype;
  previous private.training_requests%rowtype;
  job private.ship_upgrade_jobs%rowtype;
  recovered record;
  group_name text:=case when action='crew' then 'crew' when action='ship' then 'ship' else payload->>'group' end;
  stat text:=payload->>'stat';
  observed_at timestamptz;
  gain bigint; xp_gain bigint; energy_cost integer; result jsonb;
begin
  if request_id is null or action is null or action not in ('crew','ship','purchase') or payload is null then
    raise exception 'INVALID_REQUEST' using errcode='22023'; end if;
  if group_name is null or group_name not in ('crew','ship') then raise exception 'INVALID_GROUP' using errcode='22023'; end if;
  if action in ('crew','ship') and (stat is null or stat not in ('attack','defense','speed','accuracy')) then
    raise exception 'INVALID_STAT' using errcode='22023'; end if;
  perform private.settle_combat_context(array[viewer_id]);
  select * into previous from private.training_requests r where r.character_id=viewer_id and r.request_id=training_action.request_id;
  if found then
    if previous.action<>action or previous.payload<>payload then raise exception 'REQUEST_CONFLICT' using errcode='22023'; end if;
    return previous.result;
  end if;
  observed_at:=clock_timestamp();
  perform private.settle_ship_upgrade(viewer_id,observed_at);
  if exists(select 1 from private.combat_engagements where character_id=viewer_id and role='attacker') then
    raise exception 'IN_COMBAT'; end if;
  select * into captain from public.characters where id=viewer_id for update;
  if captain.location<>'the_harbor' then raise exception 'NOT_IN_HARBOR'; end if;
  select * into progress from private.character_training where character_id=viewer_id and training_group=group_name for update;
  select * into current_tier from private.training_tiers where training_group=group_name and id=progress.tier_id;
  if action='purchase' then
    select * into tier from private.training_tiers where training_group=group_name and id=payload->>'tier_id';
    if tier.id is null or tier.position<>current_tier.position+1 then raise exception 'INVALID_TIER' using errcode='22023'; end if;
    if progress.xp<tier.xp_required then raise exception 'NOT_ENOUGH_XP'; end if;
    if captain.gold_coins<tier.gold_cost then raise exception 'NOT_ENOUGH_GOLD'; end if;
    update public.characters set gold_coins=gold_coins-tier.gold_cost where id=viewer_id;
    update private.character_training set tier_id=tier.id where character_id=viewer_id and training_group=group_name;
    result:=jsonb_build_object('kind','purchase','group',group_name,'tier_id',tier.id,'tier_name',tier.name,'gold_cost',tier.gold_cost);
  else
    if payload->>'tier_id' is distinct from current_tier.id then raise exception 'STALE_TIER' using errcode='22023'; end if;
    energy_cost:=5;
    gain:=current_tier.stat_gain;
    if action='ship' then
      if exists(select 1 from private.ship_upgrade_jobs where character_id=viewer_id and applied_at is null) then raise exception 'SHIP_WORK_ACTIVE'; end if;
      select * into size from private.ship_work_sizes where id=payload->>'size_id';
      if not found then raise exception 'INVALID_SIZE' using errcode='22023'; end if;
      energy_cost:=energy_cost*size.units;
      gain:=gain*size.units;
    else
      gain:=private.crew_training_gain(gain,private.combat_roll());
    end if;
    xp_gain:=energy_cost::bigint*1;
    if (to_jsonb(captain)->>(group_name||'_'||stat))::bigint>9007199254740991-gain
      or progress.xp>9007199254740991-xp_gain then raise exception 'PROGRESSION_LIMIT'; end if;
    select * into recovered from private.energy_snapshot(captain.energy,captain.energy_updated_at,observed_at);
    if recovered.energy<energy_cost then raise exception 'NOT_ENOUGH_ENERGY'; end if;
    update public.characters set energy=recovered.energy-energy_cost,energy_updated_at=recovered.energy_updated_at where id=viewer_id;
    if action='crew' then
      execute format('update public.characters set %I=%I+$1 where id=$2','crew_'||stat,'crew_'||stat) using gain,viewer_id;
      update private.character_training set xp=xp+xp_gain where character_id=viewer_id and training_group='crew';
      result:=jsonb_build_object('kind','crew','stat',stat,'stat_gain',gain,'xp_gain',xp_gain,'energy_cost',energy_cost,
        'perfect',gain>current_tier.stat_gain,'tier_id',current_tier.id);
    else
      insert into private.ship_upgrade_jobs(character_id,stat,size_id,workshop_id,workshop_name,energy_cost,stat_gain,xp_gain,config_revision,started_at,finishes_at)
        values(viewer_id,stat,size.id,current_tier.id,current_tier.name,energy_cost,gain,xp_gain,public.get_gameplay_revision(),
          observed_at,observed_at+make_interval(secs=>size.duration_seconds)) returning * into job;
      result:=jsonb_build_object('kind','ship','job_id',job.id,'stat',stat,'stat_gain',gain,'xp_gain',xp_gain,
        'energy_cost',energy_cost,'finishes_at',job.finishes_at);
    end if;
  end if;
  insert into private.training_requests(character_id,request_id,action,payload,result) values(viewer_id,request_id,action,payload,result);
  perform private.notify_training(viewer_id);
  return result;
end;
$$;

revoke all on function private.notify_training(uuid),private.settle_ship_upgrade(uuid,timestamptz),
  private.training_state(uuid),private.crew_training_gain(bigint,double precision),private.training_action(text,jsonb,uuid)
  from public,anon,authenticated;
grant execute on function private.training_action(text,jsonb,uuid) to authenticated;

create or replace function public.train_crew(stat text,expected_tier_id text,request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.training_action('crew',jsonb_build_object('stat',stat,'tier_id',expected_tier_id),request_id);
$$;
create or replace function public.purchase_training_tier(training_group text,tier_id text,request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.training_action('purchase',jsonb_build_object('group',training_group,'tier_id',tier_id),request_id);
$$;
create or replace function public.start_ship_upgrade(stat text,size_id text,expected_workshop_id text,request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.training_action('ship',jsonb_build_object('stat',stat,'size_id',size_id,'tier_id',expected_workshop_id),request_id);
$$;
revoke all on function public.train_crew(text,text,uuid),public.purchase_training_tier(text,text,uuid),
  public.start_ship_upgrade(text,text,text,uuid) from public,anon,authenticated;
grant execute on function public.train_crew(text,text,uuid),public.purchase_training_tier(text,text,uuid),
  public.start_ship_upgrade(text,text,text,uuid) to authenticated;

-- Canonical function bodies; scalar config tokens are substituted by config tooling.
-- Existing rows and reports are preserved; incompatible lower caps abort migration.
alter table public.characters
  alter column energy set default 100,
  alter column ship_health set default 100,
  alter column crew_health set default 100,
  alter column defence_order set default 'cannon',
  drop constraint characters_energy_check,
  add constraint characters_energy_check check(energy between 0 and 100),
  drop constraint characters_ship_health_check,
  add constraint characters_ship_health_check check(ship_health between 0 and 100),
  drop constraint characters_crew_health_check,
  add constraint characters_crew_health_check check(crew_health between 0 and 100);
alter table public.characters alter column ship_attack set default 10;
alter table public.characters alter column ship_defense set default 10;
alter table public.characters alter column ship_speed set default 10;
alter table public.characters alter column ship_accuracy set default 10;
alter table public.characters alter column crew_attack set default 10;
alter table public.characters alter column crew_defense set default 10;
alter table public.characters alter column crew_speed set default 10;
alter table public.characters alter column crew_accuracy set default 10;

-- Preserve historical counters when future limits decrease.
alter table private.combat_participants
  alter column defender_ammo set default 10,
  drop constraint combat_participants_round_check,
  add constraint combat_participants_round_check check(round>=0),
  drop constraint combat_participants_defender_ammo_check,
  add constraint combat_participants_defender_ammo_check check(defender_ammo>=0);

create or replace function private.energy_snapshot(stored_energy integer, anchor timestamptz, observed_at timestamptz)
returns table (energy integer, energy_updated_at timestamptz)
language sql immutable strict security invoker set search_path = ''
as $$
  with recovery as (
    select least(100 - stored_energy,
      greatest(0, floor(extract(epoch from (observed_at - anchor)) / 300)))::integer as gained
  )
  select stored_energy + gained,
    case when stored_energy + gained = 100 then observed_at
      else anchor + gained * make_interval(secs => 300) end
  from recovery;
$$;

create or replace function private.health_snapshot(value integer, anchor timestamptz, observed_at timestamptz, seconds integer)
returns integer language sql immutable strict security invoker set search_path = ''
as $$
  select least(100, value + least(100, greatest(0, floor(extract(epoch from (observed_at - anchor)) / seconds)))::integer);
$$;

create or replace function private.combat_snapshot(c public.characters, observed_at timestamptz)
returns jsonb language sql stable security invoker set search_path = ''
as $$
  select jsonb_build_object(
    'id', c.id, 'name', c.display_name, 'ammo', 10, 'defence_order', c.defence_order,
    'ship_health', private.health_snapshot(c.ship_health, c.ship_recovery_at, observed_at, 30),
    'crew_health', private.health_snapshot(c.crew_health, c.crew_recovery_at, observed_at, 10),
    'ship', jsonb_build_object('attack',c.ship_attack,'defense',c.ship_defense,'speed',c.ship_speed,'accuracy',c.ship_accuracy),
    'crew', jsonb_build_object('attack',c.crew_attack,'defense',c.crew_defense,'speed',c.crew_speed,'accuracy',c.crew_accuracy)
  );
$$;

create or replace function private.visible_combatant(snapshot jsonb, own boolean, revealed boolean)
returns jsonb language sql immutable security invoker set search_path = ''
as $$
  select jsonb_build_object(
    'id',snapshot->'id','name',snapshot->'name',
    'ship_health',snapshot->'ship_health','crew_health',snapshot->'crew_health',
    'ammo',case when own then snapshot->'ammo' end,
    'ship',case when own then snapshot->'ship' end,
    'crew',case when own then snapshot->'crew' end,
    'cannons',case when own or revealed then 'Basic cannons' end,
    'weapon',case when own or revealed then 'Cutlasses' end);
$$;

create or replace function private.combat_hit_chance(accuracy numeric, speed numeric)
returns double precision language plpgsql immutable strict security invoker set search_path='' as $$
declare ratio double precision;
  extreme constant double precision := 64;
  exponent constant double precision := 0.5;
  factor double precision := power(extreme,exponent);
begin
  if accuracy<=0 or speed<=0 then raise exception 'INVALID_COMBAT_STAT' using errcode='22023'; end if;
  ratio:=(accuracy/speed)::double precision;
  if ratio<=1/extreme then return 0; end if;
  if ratio>=extreme then return 1; end if;
  if ratio<=1 then return (factor*power(ratio,exponent)-1)/(2*(factor-1)); end if;
  return 1-(factor*power(1/ratio,exponent)-1)/(2*(factor-1));
end;
$$;

create or replace function private.combat_damage_reduction(attack numeric, defense numeric)
returns numeric language plpgsql immutable strict security invoker set search_path='' as $$
declare ratio numeric;
  zero_ratio constant numeric := 32;
  full_ratio constant numeric := 25;
  equal_reduction constant numeric := 0.5;
begin
  if attack<=0 or defense<=0 then raise exception 'INVALID_COMBAT_STAT' using errcode='22023'; end if;
  ratio:=defense/attack;
  if ratio<=1/zero_ratio then return 0; end if;
  if ratio>=full_ratio then return 1; end if;
  if ratio<=1 then return equal_reduction*(1+ln(ratio)/ln(zero_ratio)); end if;
  return equal_reduction+(1-equal_reduction)*ln(ratio)/ln(full_ratio);
end;
$$;

create or replace function private.combat_damage(attack numeric, defense numeric)
returns integer language plpgsql immutable strict security invoker set search_path='' as $$
declare reduction numeric; strength_log numeric;
begin
  reduction:=private.combat_damage_reduction(attack,defense);
  if reduction>=1 then return 0; end if;
  strength_log:=log(greatest(1::numeric,attack/1));
  return greatest(1,round(
    (7*strength_log*strength_log+
     27*strength_log+30)*(1-reduction)))::integer;
end;
$$;

create or replace function private.resolve_combat_round(input_state jsonb, player_order text, rolls double precision[])
returns jsonb language plpgsql immutable security invoker set search_path = ''
as $$
declare
  a jsonb := input_state->'attacker';
  d jsonb := input_state->'defender';
  phase text := input_state->>'phase';
  group_name text := case when phase = 'sea' then 'ship' else 'crew' end;
  health_key text := group_name || '_health';
  defender_order text;
  next_phase text := phase;
  round_no integer := (input_state->>'round')::integer + 1;
  a_damage integer := 0; d_damage integer := 0;
  a_hit boolean := false; d_hit boolean := false;
  chance double precision;
  a_down boolean; d_down boolean;
  outcome text; winner text; transition text;
  boarded boolean;
  result_state jsonb;
begin
  if input_state->>'status' <> 'active' or round_no > 25 then raise exception 'COMBAT_FINISHED'; end if;
  if player_order is null or
    (phase = 'sea' and player_order not in ('fire', 'board', 'retreat')) or
    (phase = 'boarding' and player_order not in ('crew_attack', 'disengage', 'retreat')) then
    raise exception 'INVALID_ORDER' using errcode = '22023';
  end if;
  if cardinality(rolls) <> 3 or exists(select 1 from unnest(rolls) r where r is null or r < 0 or r >= 1) then
    raise exception 'INVALID_ROLLS';
  end if;
  defender_order := case when phase = 'boarding' then 'crew_attack'
    when d->>'defence_order' = 'cannon' and (d->>'ammo')::integer >= 1 then 'fire' else 'board' end;
  if player_order = 'fire' and (a->>'ammo')::integer < 1 then raise exception 'NO_AMMO'; end if;
  if player_order in ('fire', 'crew_attack') then
    chance := private.combat_hit_chance((a->group_name->>'accuracy')::numeric,(d->group_name->>'speed')::numeric);
    a_hit := rolls[1] < chance;
    if a_hit then a_damage := least((d->>health_key)::integer,
      private.combat_damage((a->group_name->>'attack')::numeric,(d->group_name->>'defense')::numeric)); end if;
  end if;
  if defender_order in ('fire', 'crew_attack') then
    chance := private.combat_hit_chance((d->group_name->>'accuracy')::numeric,(a->group_name->>'speed')::numeric);
    d_hit := rolls[2] < chance;
    if d_hit then d_damage := least((a->>health_key)::integer,
      private.combat_damage((d->group_name->>'attack')::numeric,(a->group_name->>'defense')::numeric)); end if;
  end if;
  a := a || jsonb_build_object(health_key, (a->>health_key)::integer - d_damage,
    'ammo', (a->>'ammo')::integer - case when player_order = 'fire' then 1 else 0 end);
  d := d || jsonb_build_object(health_key, (d->>health_key)::integer - a_damage,
    'ammo', (d->>'ammo')::integer - case when defender_order = 'fire' then 1 else 0 end);
  a_down := (a->>'ship_health')::integer = 0 or (a->>'crew_health')::integer = 0;
  d_down := (d->>'ship_health')::integer = 0 or (d->>'crew_health')::integer = 0;
  if a_down and d_down then outcome := 'draw';
  elsif a_down or d_down then
    outcome := case when phase = 'sea' then 'hull_victory' else 'boarding_victory' end;
    winner := case when a_down then d->>'id' else a->>'id' end;
  elsif player_order = 'retreat' then outcome := 'retreated';
  elsif round_no >= 25 then outcome := 'draw';
  elsif phase = 'boarding' and player_order = 'disengage' then
    next_phase := 'sea'; transition := 'disengaged';
  elsif phase = 'sea' and (player_order = 'board' or defender_order = 'board') then
    if player_order = 'board' and defender_order = 'board' then boarded := true;
    else
      chance := greatest(0.2, least(0.9, 0.7 + 0.3 *
        ((a->'ship'->>'speed')::double precision - (d->'ship'->>'speed')::double precision) /
        ((a->'ship'->>'speed')::double precision + (d->'ship'->>'speed')::double precision) *
        case when player_order = 'board' then 1 else -1 end));
      boarded := rolls[3] < chance;
    end if;
    transition := case when boarded then 'boarded' else 'boarding_failed' end;
    if boarded then next_phase := 'boarding'; end if;
  end if;
  result_state := input_state || jsonb_build_object('attacker',a,'defender',d,'round',round_no,'phase',next_phase,
    'status',case when outcome is null then 'active' else 'completed' end,
    'outcome',outcome,'winner_id',winner);
  return jsonb_build_object('state',result_state,'event',jsonb_build_object(
    'round',round_no,'phase',phase,'attacker_order',player_order,'defender_order',defender_order,
    'attacker_hit',a_hit,'defender_hit',d_hit,'attacker_damage',a_damage,'defender_damage',d_damage,
    'transition',transition,'outcome',outcome));
end;
$$;

create or replace function private.advance_shared_combat(battle_id uuid, actor uuid, player_order text, request_id uuid, occurred_at timestamptz, timed_out boolean)
returns void language plpgsql volatile security invoker set search_path='' as $$
declare b private.combats%rowtype; p private.combat_participants%rowtype;
  resolved jsonb; s jsonb; d jsonb; a jsonb; personal_status text; ending text; winner uuid;
begin
  select * into b from private.combats where id=battle_id for update;
  select * into p from private.combat_participants where combat_id=battle_id and character_id=actor;
  if b.status<>'active' or p.status<>'active' then return; end if;
  resolved:=private.resolve_combat_round(jsonb_build_object('status','active','phase',p.phase,'round',p.round,
    'attacker',p.snapshot,'defender',b.state->'defender' || jsonb_build_object('ammo',p.defender_ammo)),
    player_order,array[private.combat_roll(),private.combat_roll(),private.combat_roll()]);
  s:=resolved->'state'; a:=s->'attacker'; d:=s->'defender';
  personal_status:=case
    when (a->>'ship_health')::integer=0 or (a->>'crew_health')::integer=0 then 'defeated'
    when player_order='retreat' then 'retreated'
    when (s->>'round')::integer>=25 then 'draw' else 'active' end;
  -- Final blow remains credited even if the simultaneous counterattack also downs its author.
  if (d->>'ship_health')::integer=0 or (d->>'crew_health')::integer=0 then
    ending:=case when (d->>'ship_health')::integer=0 then 'hull_victory' else 'boarding_victory' end;
    winner:=actor; personal_status:='victory';
  end if;
  update private.combat_participants set snapshot=a,phase=s->>'phase',round=(s->>'round')::integer,
    status=personal_status,defender_ammo=(d->>'ammo')::integer,
    deadline=least(b.hard_deadline,occurred_at+make_interval(secs => 120)),
    finished_at=case when personal_status<>'active' then occurred_at end,
    hits=hits+case when (resolved->'event'->>'attacker_hit')::boolean then 1 else 0 end,
    damage=damage+(resolved->'event'->>'attacker_damage')::integer
    where combat_id=battle_id and character_id=actor;
  update public.characters set ship_health=(a->>'ship_health')::integer,crew_health=(a->>'crew_health')::integer,
    ship_recovery_at=occurred_at,crew_recovery_at=occurred_at,
    protected_until=case when personal_status<>'active' then occurred_at+make_interval(secs => 300) end where id=actor;
  update public.characters set ship_health=(d->>'ship_health')::integer,crew_health=(d->>'crew_health')::integer,
    ship_recovery_at=occurred_at,crew_recovery_at=occurred_at where id=b.defender_id;
  if personal_status<>'active' then delete from private.combat_engagements where character_id=actor and combat_id=battle_id; end if;
  if ending is not null then
    update public.characters set ship_recovery_at=occurred_at,crew_recovery_at=occurred_at,protected_until=occurred_at+make_interval(secs => 300)
      where id in(select character_id from private.combat_participants where combat_id=battle_id and status='active');
    update private.combat_participants set status='assist',finished_at=occurred_at where combat_id=battle_id and status='active';
  elsif not exists(select 1 from private.combat_participants where combat_id=battle_id and status='active') then
    ending:=case when personal_status='defeated' then 'defended' when personal_status='draw' then 'draw' else 'retreated' end;
    winner:=case when personal_status='defeated' then b.defender_id end;
  end if;
  perform private.append_combat_event(battle_id,actor,request_id,
    resolved->'event' || jsonb_build_object('kind','round','actor_name',p.snapshot->>'name',
      'at',occurred_at,'timed_out',timed_out,'participant_result',personal_status,'outcome',ending));
  update private.combats set state=state || jsonb_build_object('defender',d,'status',case when ending is null then 'active' else 'completed' end,
    'outcome',ending,'winner_id',winner),
    deadline=coalesce((select min(deadline) from private.combat_participants where combat_id=battle_id and status='active'),occurred_at),
    finished_at=case when ending is not null then occurred_at end where id=battle_id;
  if ending is not null then
    delete from private.combat_engagements where combat_id=battle_id;
    update public.characters set protected_until=occurred_at+make_interval(secs => 300) where id=b.defender_id;
  end if;
  perform private.notify_combat(battle_id);
end;
$$;

create or replace function private.get_combat_preview(target_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare viewer_id uuid:=private.combat_captain(); a public.characters%rowtype; d public.characters%rowtype;
  own_engagement private.combat_engagements%rowtype; target_engagement private.combat_engagements%rowtype;
  a_snapshot jsonb; d_snapshot jsonb; energy_now integer; reason text; observed_at timestamptz;
begin
  if target_id is null then return jsonb_build_object('error','CHARACTER_NOT_FOUND'); end if;
  perform private.settle_combat_context(array[viewer_id,target_id]);
  observed_at:=clock_timestamp();
  perform private.settle_ship_upgrade(viewer_id,observed_at);
  perform private.settle_ship_upgrade(target_id,observed_at);
  select * into a from public.characters where id=viewer_id;
  select * into d from public.characters where id=target_id;
  if d.id is null then return jsonb_build_object('error','CHARACTER_NOT_FOUND'); end if;
  select * into own_engagement from private.combat_engagements where character_id=viewer_id;
  select * into target_engagement from private.combat_engagements where character_id=target_id;
  a_snapshot:=private.combat_snapshot(a,observed_at);
  d_snapshot:=private.combat_snapshot(d,observed_at);
  if own_engagement.character_id is not null then a_snapshot:=a_snapshot || jsonb_build_object('ship_health',a.ship_health,'crew_health',a.crew_health); end if;
  if target_engagement.character_id is not null then d_snapshot:=d_snapshot || jsonb_build_object('ship_health',d.ship_health,'crew_health',d.crew_health); end if;
  select energy into energy_now from private.energy_snapshot(a.energy,a.energy_updated_at,observed_at);
  reason:=case when viewer_id=target_id then 'SELF_ATTACK'
    when own_engagement.role='attacker' then 'IN_COMBAT'
    when own_engagement.role='defender' then 'DEFENDING'
    when target_engagement.role='attacker' then 'TARGET_IN_COMBAT'
    when exists(select 1 from private.combat_participants where combat_id=target_engagement.combat_id and character_id=viewer_id) then 'ALREADY_PARTICIPATED'
    when target_engagement.character_id is null and d.protected_until>observed_at then 'TARGET_PROTECTED'
    when (a_snapshot->>'ship_health')::integer<1 or (a_snapshot->>'crew_health')::integer<1 then 'NO_HEALTH'
    when (d_snapshot->>'ship_health')::integer<1 or (d_snapshot->>'crew_health')::integer<1 then 'TARGET_NO_HEALTH'
    when energy_now<10 then 'NOT_ENOUGH_ENERGY' end;
  return jsonb_build_object('attacker',private.visible_combatant(a_snapshot,true,false),
    'defender',private.visible_combatant(d_snapshot,false,false),'energy',energy_now,'can_start',reason is null,'reason',reason,
    'active_combat_id',case when own_engagement.role='attacker' then own_engagement.combat_id end,
    'join_combat_id',case when target_engagement.role='defender' then target_engagement.combat_id end,
    'target_protected_until',case when target_engagement.character_id is null and d.protected_until>observed_at then d.protected_until end,
    'observed_at',observed_at);
end;
$$;

create or replace function private.start_combat(target_id uuid,request_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare viewer_id uuid:=private.combat_captain(); previous private.combat_participants%rowtype;
  preview jsonb; a public.characters%rowtype; d public.characters%rowtype; recovered record;
  battle_id uuid; initial_state jsonb; observed_at timestamptz; b private.combats%rowtype; snapshot jsonb; joining boolean;
begin
  if request_id is null then raise exception 'INVALID_REQUEST' using errcode='22023'; end if;
  perform private.settle_combat_context(array[viewer_id,target_id]);
  select * into previous from private.combat_participants where character_id=viewer_id and start_request_id=request_id;
  if found then
    if (select defender_id from private.combats where id=previous.combat_id)<>target_id then return jsonb_build_object('error','REQUEST_CONFLICT'); end if;
    return jsonb_build_object('battle',private.combat_view(previous.combat_id,viewer_id));
  end if;
  preview:=private.get_combat_preview(target_id);
  if preview ? 'error' then return preview; end if;
  if not (preview->>'can_start')::boolean then return jsonb_build_object('error',preview->>'reason'); end if;
  observed_at:=clock_timestamp();
  perform private.settle_ship_upgrade(viewer_id,observed_at);
  perform private.settle_ship_upgrade(target_id,observed_at);
  select * into a from public.characters where id=viewer_id;
  select * into d from public.characters where id=target_id;
  select * into recovered from private.energy_snapshot(a.energy,a.energy_updated_at,observed_at);
  snapshot:=private.combat_snapshot(a,observed_at);
  battle_id:=(preview->>'join_combat_id')::uuid; joining:=battle_id is not null;
  if not joining then
    initial_state:=jsonb_build_object('attacker',snapshot,'defender',private.combat_snapshot(d,observed_at),
      'status','active','outcome',null,'winner_id',null);
    insert into private.combats(attacker_id,defender_id,start_request_id,rules_version,state,started_at,deadline,hard_deadline)
      values(viewer_id,target_id,request_id,2,initial_state,observed_at,observed_at+make_interval(secs => 120),observed_at+make_interval(secs => 600))
      returning id into battle_id;
    insert into private.combat_engagements(character_id,combat_id,role) values(target_id,battle_id,'defender');
    update public.characters set protected_until=null,ship_health=(initial_state->'defender'->>'ship_health')::integer,
      crew_health=(initial_state->'defender'->>'crew_health')::integer,ship_recovery_at=observed_at,crew_recovery_at=observed_at where id=target_id;
  end if;
  select * into b from private.combats where id=battle_id for update;
  insert into private.combat_participants(combat_id,character_id,start_request_id,snapshot,joined_at,deadline)
    values(battle_id,viewer_id,request_id,snapshot,observed_at,least(b.hard_deadline,observed_at+make_interval(secs => 120)));
  insert into private.combat_engagements(character_id,combat_id,role) values(viewer_id,battle_id,'attacker');
  update public.characters set energy=recovered.energy-10,energy_updated_at=recovered.energy_updated_at,protected_until=null,
    ship_health=(snapshot->>'ship_health')::integer,crew_health=(snapshot->>'crew_health')::integer,
    ship_recovery_at=observed_at,crew_recovery_at=observed_at where id=viewer_id;
  perform private.append_combat_event(battle_id,viewer_id,request_id,jsonb_build_object(
    'kind',case when joining then 'joined' else 'started' end,'actor_name',a.display_name,'at',observed_at));
  perform private.notify_combat(battle_id);
  return jsonb_build_object('battle',private.combat_view(battle_id,viewer_id));
end;
$$;

create or replace function private.submit_combat_order(battle_id uuid,expected_round integer,player_order text,request_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare viewer_id uuid:=private.combat_captain(); b private.combats%rowtype; p private.combat_participants%rowtype; previous jsonb;
begin
  if request_id is null or expected_round is null or expected_round<0 or expected_round>=25 then raise exception 'INVALID_REQUEST' using errcode='22023'; end if;
  select * into b from private.combats where id=battle_id;
  if not found or not exists(select 1 from private.combat_participants where combat_id=battle_id and character_id=viewer_id) then
    return jsonb_build_object('error','COMBAT_NOT_FOUND'); end if;
  perform private.settle_combat_context(array[viewer_id,b.defender_id]);
  select * into b from private.combats where id=battle_id;
  select * into p from private.combat_participants where combat_id=battle_id and character_id=viewer_id;
  select event into previous from private.combat_rounds where combat_id=battle_id and actor_id=viewer_id and combat_rounds.request_id=submit_combat_order.request_id;
  if found then
    if previous->>'kind'<>'round' or (previous->>'round')::integer<>expected_round+1 or previous->>'attacker_order'<>player_order then
      return jsonb_build_object('error','REQUEST_CONFLICT'); end if;
    return jsonb_build_object('battle',private.combat_view(battle_id,viewer_id));
  end if;
  if b.status='completed' or p.status<>'active' then return jsonb_build_object('battle',private.combat_view(battle_id,viewer_id)); end if;
  if p.round<>expected_round then return jsonb_build_object('error','STALE_ROUND'); end if;
  if player_order is null or (p.phase='sea' and player_order not in ('fire','board','retreat'))
    or (p.phase='boarding' and player_order not in ('crew_attack','disengage','retreat')) then return jsonb_build_object('error','INVALID_ORDER'); end if;
  if player_order='fire' and (p.snapshot->>'ammo')::integer<1 then return jsonb_build_object('error','NO_AMMO'); end if;
  perform private.advance_shared_combat(battle_id,viewer_id,player_order,request_id,clock_timestamp(),false);
  return jsonb_build_object('battle',private.combat_view(battle_id,viewer_id));
end;
$$;

create or replace function private.get_game_state()
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare c public.characters%rowtype; active private.combats%rowtype; engagement private.combat_engagements%rowtype; observed_at timestamptz;
  recovered record; ship_hp integer; crew_hp integer; health_next_at timestamptz; last_id uuid;
begin
  if auth.uid() is null or not private.is_registered_player() then return null; end if;
  select * into c from public.characters where user_id=auth.uid();
  if not found then return null; end if;
  perform private.settle_combat_context(array[c.id]);
  observed_at:=clock_timestamp();
  perform private.settle_ship_upgrade(c.id,observed_at);
  select * into c from public.characters where id=c.id;
  select * into engagement from private.combat_engagements where character_id=c.id;
  select * into active from private.combats where id=engagement.combat_id;
  select * into recovered from private.energy_snapshot(c.energy,c.energy_updated_at,observed_at);
  ship_hp:=case when active.id is not null then c.ship_health else private.health_snapshot(c.ship_health,c.ship_recovery_at,observed_at,30) end;
  crew_hp:=case when active.id is not null then c.crew_health else private.health_snapshot(c.crew_health,c.crew_recovery_at,observed_at,10) end;
  if active.id is null then
    health_next_at:=least(case when ship_hp<100 then c.ship_recovery_at+(ship_hp-c.ship_health+1)*make_interval(secs => 30) end,
      case when crew_hp<100 then c.crew_recovery_at+(crew_hp-c.crew_health+1)*make_interval(secs => 10) end);
  end if;
  select b.id into last_id from private.combats b where b.defender_id=c.id
    or exists(select 1 from private.combat_participants where combat_id=b.id and character_id=c.id)
    order by b.started_at desc,b.id desc limit 1;
  return jsonb_build_object('energy',recovered.energy,'energy_next_at',case when recovered.energy<100 then recovered.energy_updated_at+make_interval(secs => 300) end,
    'gold_coins',c.gold_coins,'bank_gold_coins',c.bank_gold_coins,'training',private.training_state(c.id),
    'observed_at',observed_at,'ship_health',ship_hp,'crew_health',crew_hp,'health_next_at',health_next_at,
    'active_combat_id',active.id,'combat_next_at',active.deadline,'last_combat_id',last_id,
    'active_attack',case when engagement.role='attacker' then jsonb_build_object('battle_id',active.id,'target_id',active.defender_id) end,
    'defence_order',c.defence_order,'protected_until',case when c.protected_until>observed_at then c.protected_until end,
    'ship_attack',c.ship_attack,'ship_defense',c.ship_defense,'ship_speed',c.ship_speed,'ship_accuracy',c.ship_accuracy,
    'crew_attack',c.crew_attack,'crew_defense',c.crew_defense,'crew_speed',c.crew_speed,'crew_accuracy',c.crew_accuracy);
end;
$$;


create or replace function public.list_harbor_players(requested_page integer default 0)
returns jsonb
language sql stable security invoker set search_path = ''
as $$
  with totals as (
    select count(*)::integer as total from public.harbor_players
  ), paging as (
    select total, least(greatest(coalesce(requested_page, 0), 0),
      greatest(0, (total - 1) / 20)) as page from totals
  )
  select jsonb_build_object(
    'total', total, 'page', page,
    'players', coalesce((
      select jsonb_agg(to_jsonb(player) order by player.display_name, player.character_id)
      from (
        select character_id, display_name from public.harbor_players
        order by display_name, character_id limit 20 offset paging.page * 20
      ) player
    ), '[]'::jsonb)
  ) from paging;
$$;

-- Gold Coins are separate carried and bank balances.
alter table public.characters
  alter column gold_coins set default 0,
  drop constraint characters_gold_coins_check,
  add constraint characters_gold_coins_check check (gold_coins between 0 and 9007199254740991),
  drop constraint characters_bank_gold_coins_check,
  add constraint characters_bank_gold_coins_check check (bank_gold_coins between 0 and 9007199254740991);

create or replace function private.transfer_gold(direction text, amount numeric, request_id uuid)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare
  viewer_id uuid := private.combat_captain();
  captain public.characters%rowtype;
  previous private.bank_transfers%rowtype;
  coins bigint;
begin
  if request_id is null then raise exception 'INVALID_REQUEST' using errcode='22023'; end if;
  if direction is null or direction not in ('deposit','withdraw') then
    raise exception 'INVALID_DIRECTION' using errcode='22023'; end if;
  if amount is null or amount < 1 or amount > 9007199254740991 or amount <> trunc(amount) then
    raise exception 'INVALID_AMOUNT' using errcode='22023'; end if;
  coins := amount::bigint;
  perform private.settle_combat_context(array[viewer_id]);
  select * into previous from private.bank_transfers t
    where t.character_id=viewer_id and t.request_id=transfer_gold.request_id;
  if found then
    if previous.direction <> direction or previous.amount <> coins then
      raise exception 'REQUEST_CONFLICT' using errcode='22023';
    end if;
    return jsonb_build_object('direction',previous.direction,'amount',previous.amount,
      'gold_coins',previous.gold_coins,'bank_gold_coins',previous.bank_gold_coins);
  end if;
  if exists(select 1 from private.combat_engagements where character_id=viewer_id and role='attacker') then
    raise exception 'IN_COMBAT' using errcode='P0001'; end if;
  select * into captain from public.characters where id=viewer_id for update;
  if captain.location <> 'the_harbor' then raise exception 'NOT_IN_HARBOR' using errcode='P0001'; end if;
  if direction='deposit' then
    if captain.gold_coins < coins then raise exception 'NOT_ENOUGH_GOLD' using errcode='P0001'; end if;
    if captain.bank_gold_coins > 9007199254740991 - coins then
      raise exception 'BALANCE_LIMIT' using errcode='P0001'; end if;
    update public.characters set gold_coins=gold_coins-coins, bank_gold_coins=bank_gold_coins+coins
      where id=viewer_id returning * into captain;
  else
    if captain.bank_gold_coins < coins then raise exception 'NOT_ENOUGH_BANK_GOLD' using errcode='P0001'; end if;
    if captain.gold_coins > 9007199254740991 - coins then
      raise exception 'BALANCE_LIMIT' using errcode='P0001'; end if;
    update public.characters set gold_coins=gold_coins+coins, bank_gold_coins=bank_gold_coins-coins
      where id=viewer_id returning * into captain;
  end if;
  insert into private.bank_transfers(character_id,request_id,direction,amount,gold_coins,bank_gold_coins)
    values(viewer_id,request_id,direction,coins,captain.gold_coins,captain.bank_gold_coins);
  insert into public.player_game_events(character_id,revision) values(viewer_id,1)
    on conflict(character_id) do update set revision=player_game_events.revision+1;
  return jsonb_build_object('direction',direction,'amount',coins,
    'gold_coins',captain.gold_coins,'bank_gold_coins',captain.bank_gold_coins);
end;
$$;
revoke all on function private.transfer_gold(text,numeric,uuid) from public,anon,authenticated;
grant execute on function private.transfer_gold(text,numeric,uuid) to authenticated;

create or replace function public.transfer_gold(direction text, amount numeric, request_id uuid)
returns jsonb language sql volatile security invoker set search_path='' as $$
  select private.transfer_gold(direction,amount,request_id);
$$;
revoke all on function public.transfer_gold(text,numeric,uuid) from public,anon,authenticated;
grant execute on function public.transfer_gold(text,numeric,uuid) to authenticated;

create or replace function public.get_gameplay_revision()
returns text language sql immutable security invoker set search_path='' as $$
  select '26c391f022e6f6cb8c4758b2a49697efc0e8302455d8f8e59c72a8434d92a624'::text;
$$;
revoke all on function public.get_gameplay_revision() from public;
grant execute on function public.get_gameplay_revision() to anon,authenticated;
